from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_LUNAR_LANDER_MULTI_GA(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.LUNAR_LANDER_V2
    DEEP_LEARNING_MODEL = DeepLearningModelName.SIMPLE_MLP
    RL_ALGORITHM = RLAlgorithmName.MULTI_GENETIC_ALGORITHM
    OPTIMIZER = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 300.0
    STOP_PATIENCE_COUNT = 10

    LEARNING_RATE = 0.001
    NOISE_STANDARD_DEVIATION = 0.01

    POPULATION_SIZE = 2000
    PARENTS_COUNT = 10

    WORKERS_COUNT = 6
    MAX_SEED = 2**32 - 1
    SEEDS_PER_WORKER = POPULATION_SIZE // WORKERS_COUNT