from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_CARTPOLE_GA(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.CARTPOLE_V1
    RL_ALGORITHM = RLAlgorithmName.GENETIC_ALGORITHM
    DEEP_LEARNING_MODEL = DeepLearningModelName.SIMPLE_MLP

    POPULATION_SIZE = 50
    PARENTS_COUNT = 3

    STOP_MEAN_EPISODE_REWARD = 195.0
    STOP_PATIENCE_COUNT = 10

    LEARNING_RATE = 0.001

    NOISE_STANDARD_DEVIATION = 0.01
