from codes.a_config._rl_parameters.off_policy.parameter_ddpg import PARAMETERS_DDPG
from codes.a_config.parameters_general import PARAMETERS_GENERAL
from codes.e_utils.names import EnvironmentName, DeepLearningModelName, RLAlgorithmName, OptimizerName


class PARAMETERS_PENDULUM_DDPG(PARAMETERS_GENERAL, PARAMETERS_DDPG):
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_MLP
    # DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_GRU
    # DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_GRU_ATTENTION
    RL_ALGORITHM = RLAlgorithmName.DDPG_V0
    OPTIMIZER = OptimizerName.ADAM

    TRAIN_STOP_EPISODE_REWARD = -200
    TRAIN_STOP_EPISODE_REWARD_STD = 50

    STOP_PATIENCE_COUNT = 10

    REPLAY_BUFFER_SIZE = 100000
    MAX_GLOBAL_STEP = 250000
    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.001
    TRAIN_STEP_FREQ = 1
    GAMMA = 0.99

    BATCH_SIZE = 128
    MIN_REPLAY_SIZE_FOR_TRAIN = 2048

    AVG_STEP_SIZE_FOR_TRAIN_LOSS = 50
    AVG_EPISODE_SIZE_FOR_STAT = 50
    N_STEP = 4
    OMEGA = False

    CLIP_GRAD = 0.1

    ACTION_SCALE = 2.0