from codes.a_config._rl_parameters.on_policy.parameter_ppo import PARAMETERS_PPO
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_LUNAR_LANDER_PPO(PARAMETERS_GENERAL, PARAMETERS_PPO):
    ENVIRONMENT_ID = EnvironmentName.LUNAR_LANDER_V2
    DEEP_LEARNING_MODEL = DeepLearningModelName.STOCHASTIC_DISCRETE_ACTOR_CRITIC_MLP
    RL_ALGORITHM = RLAlgorithmName.DISCRETE_PPO_V0
    OPTIMIZER = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 200.0
    STOP_PATIENCE_COUNT = 10

    MAX_GLOBAL_STEP = 10000000
    GAMMA = 0.99
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 50

    CLIP_GRAD = 0.5

    ## PPO
    PPO_GAE_LAMBDA = 0.95
    PPO_TRAJECTORY_SIZE = 2049
    PPO_TRAJECTORY_BATCH_SIZE = 32
    ACTOR_LEARNING_RATE = 0.0001
    LEARNING_RATE = 0.001
    PPO_K_EPOCHS = 10
    PPO_EPSILON_CLIP = 0.2
    TRAIN_STEP_FREQ = 1
    N_STEP = 1
