from codes.a_config._rl_parameters.off_policy.parameter_dqn import PARAMETERS_DQN
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_TRADE_DQN(PARAMETERS_GENERAL, PARAMETERS_DQN):
    ENVIRONMENT_ID = EnvironmentName.TRADE_V0
    RL_ALGORITHM = RLAlgorithmName.DQN_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_SMALL_CNN

    TRAIN_STOP_EPISODE_REWARD = 1000000
    STOP_PATIENCE_COUNT = 20

    MAX_GLOBAL_STEP = 3000000
    EPSILON_MIN_STEP = 600000

    REPLAY_BUFFER_SIZE = 1000000
    TARGET_NET_SYNC_STEP_PERIOD = 1000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.001
    LEARNING_RATE = 0.0001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 8
    AVG_EPISODE_SIZE_FOR_STAT = 50
    N_STEP = 1
    OMEGA = False

    TEST_PERIOD_EPISODE = 2000