import enum


class DDPGActionSelectorType(enum.Enum):
    BASIC_ACTION_SELECTOR = 0
    SOMETIMES_BLOW_ACTION_SELECTOR = 1
    NOISY_NET_ACTION_SELECTOR = 2


class DDPGActionType(enum.Enum):
    ONLY_OU_NOISE = 0
    EPSILON = 1
    UNCERTAINTY = 2
    ONLY_GREEDY = 3


class DDPGTrainType(enum.Enum):
    OLD = 0
    NEW = 1


class DDPGTargetUpdateOnlyAfterEpisode(enum.Enum):
    SOFT_UPDATE = 0
    HARD_UPDATE = 1


class PARAMETERS_DDPG:
    ENVIRONMENT_ID = None
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False
    DOUBLE = True

    REPLAY_BUFFER_SIZE = None
    ACTION_SCALE = 1.0
    TAU = 0.001

    NOISE_ENABLED = True
    OU_SIGMA = 0.2

    COUNT_BASED_EXPLORATION = True
    COUNT_BASED_FILTER = None
    COUNT_BASED_REWARD_SCALE = 0.1
    COUNT_BASED_PRECISION = 0

    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01
    EPSILON_MIN_STEP = 1000000

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = None

    TYPE_OF_ACTION = DDPGActionType.EPSILON  # current
    TYPE_OF_DDPG_TRAIN = DDPGTrainType.NEW  # current
    TYPE_OF_DDPG_ACTION_SELECTOR = DDPGActionSelectorType.BASIC_ACTION_SELECTOR
    TYPE_OF_DDPG_TARGET_UPDATE = DDPGTargetUpdateOnlyAfterEpisode.SOFT_UPDATE

    N_STEP = 2

    NOISY_NET = False
