class PARAMETERS_DQN:
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False
    DOUBLE = True

    EPSILON_INIT = None
    EPSILON_MIN = None
    EPSILON_MIN_STEP = None

    REPLAY_BUFFER_SIZE = None

    OMEGA = False
    OMEGA_WINDOW_SIZE = None

    NOISY_NET = False
    TRAIN_ONLY_AFTER_EPISODE = False

    DISTRIBUTIONAL = False
    NUM_SUPPORTS = 51
    VALUE_MIN = -10
    VALUE_MAX = 10
