class PARAMETERS_DDPG:
    ENVIRONMENT_ID = None
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False
    DOUBLE = True

    REPLAY_BUFFER_SIZE = None
    ACTION_SCALE = 1.0
    TAU = 0.001

    OU_NOISE_ENABLED = False
    OU_SIGMA = 0.2
    COUNT_BASED_EXPLORATION = True
    COUNT_BASED_REWARD_SCALE = 0.1
    COUNT_BASED_PRECISION = 0

