from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_PONG_EMAES(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PONG_NO_FRAME_SKIP_V4
    RL_ALGORITHM = RLAlgorithmName.EVOLUTION_STRATEGY
    DEEP_LEARNING_MODEL = DeepLearningModelName.SIMPLE_CNN

    TRAIN_STOP_EPISODE_REWARD = 21.0
    STOP_PATIENCE_COUNT = 10

    LEARNING_RATE = 0.001

    MAX_BATCH_EPISODES = 100
    NOISE_STANDARD_DEVIATION = 0.01
    MAX_BATCH_STEPS = 10000
