from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_PONG_MULTI_GA(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PONG_NO_FRAME_SKIP_V4
    DEEP_LEARNING_MODEL = DeepLearningModelName.SIMPLE_CNN
    RL_ALGORITHM = RLAlgorithmName.MULTI_GENETIC_ALGORITHM

    STOP_MEAN_EPISODE_REWARD = 20.0
    STOP_PATIENCE_COUNT = 10

    LEARNING_RATE = 0.001
    NOISE_STANDARD_DEVIATION = 0.01

    COUNT_FROM_PARENTS = 10

    WORKERS_COUNT = 4
    MAX_SEED = 2**32 - 1
    NUM_SEEDS_PER_WORKER = 50
    POPULATION_SIZE = NUM_SEEDS_PER_WORKER * WORKERS_COUNT
