from codes.a_config._rl_parameters.off_policy.parameter_dqn import PARAMETERS_DQN
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_BREAKOUT_DQN(PARAMETERS_GENERAL, PARAMETERS_DQN):
    ENVIRONMENT_ID = EnvironmentName.BREAKOUT_NO_FRAME_SKIP_V4
    # ENVIRONMENT_ID = EnvironmentName.BREAKOUT_DETERMINISTIC_V4
    RL_ALGORITHM = RLAlgorithmName.DQN_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_CNN

    TRAIN_STOP_EPISODE_REWARD = 500.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1000000
    TARGET_NET_SYNC_STEP_PERIOD = 10000
    MAX_GLOBAL_STEP = 20000000
    EPSILON_MIN_STEP = 2000000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.02
    # LEARNING_RATE = 0.00025
    LEARNING_RATE = 0.00001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 4
    AVG_EPISODE_SIZE_FOR_STAT = 50
    N_STEP = 1

    OMEGA = False
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False
    DOUBLE = True