from codes.a_config._rl_parameters.on_policy.parameter_ppo import PARAMETERS_PPO
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_PONG_PPO(PARAMETERS_GENERAL, PARAMETERS_PPO):
    ENVIRONMENT_ID = EnvironmentName.PONG_NO_FRAME_SKIP_V4
    DEEP_LEARNING_MODEL = DeepLearningModelName.STOCHASTIC_DISCRETE_ACTOR_CRITIC_CNN
    RL_ALGORITHM = RLAlgorithmName.DISCRETE_PPO_V0
    OPTIMIZER = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 20.0
    STOP_PATIENCE_COUNT = 10

    MAX_GLOBAL_STEP = 30000000
    GAMMA = 0.99
    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50
    CLIP_GRAD = 0.1

    ## PPO
    PPO_GAE_LAMBDA = 0.70
    PPO_TRAJECTORY_SIZE = 4097
    PPO_TRAJECTORY_BATCH_SIZE = 256
    ACTOR_LEARNING_RATE = 0.0001
    LEARNING_RATE = 0.0003
    PPO_K_EPOCHS = 4
    PPO_EPSILON_CLIP = 0.2
    TRAIN_STEP_FREQ = 1
    N_STEP = 1