from codes.a_config._rl_parameters.off_policy.parameter_dqn import PARAMETERS_DQN
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_PONG_DQN(PARAMETERS_GENERAL, PARAMETERS_DQN):
    ENVIRONMENT_ID = EnvironmentName.PONG_NO_FRAME_SKIP_V4
    RL_ALGORITHM = RLAlgorithmName.DQN_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_CNN

    STOP_MEAN_EPISODE_REWARD = 21.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 100000
    TARGET_NET_SYNC_STEP_PERIOD = 1000
    MAX_GLOBAL_STEP = 2000000
    EPSILON_MIN_STEP = 300000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.02
    LEARNING_RATE = 0.0001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 4
    AVG_EPISODE_SIZE_FOR_STAT = 50
    DATA_SAVE_STEP_PERIOD = 1000
    N_STEP = 1
    OMEGA = False
    NEXT_STATE_IN_TRAJECTORY = False
