# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dummy_grpc_pb2 as dummy__grpc__pb2


class DUMMYStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test = channel.unary_unary(
                '/DUMMY/test',
                request_serializer=dummy__grpc__pb2.Request.SerializeToString,
                response_deserializer=dummy__grpc__pb2.Response.FromString,
                )


class DUMMYServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DUMMYServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test': grpc.unary_unary_rpc_method_handler(
                    servicer.test,
                    request_deserializer=dummy__grpc__pb2.Request.FromString,
                    response_serializer=dummy__grpc__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DUMMY', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DUMMY(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DUMMY/test',
            dummy__grpc__pb2.Request.SerializeToString,
            dummy__grpc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
