from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FEDERATED_MATLAB_RIP_D4PG(PARAMETERS_GENERAL):
    # [GENERAL]
    SEED = 1
    MY_PLATFORM = OSName.MAC
    PYTHON_PATH = "~/anaconda/envs/rl/bin/python"

    # [TRANSFER]
    SOFT_TRANSFER = True
    SOFT_TRANSFER_TAU = 0.3

    # [TARGET_UPDATE]
    SOFT_TARGET_UPDATE = False
    SOFT_TARGET_UPDATE_TAU = 0.3

    # [WORKER]
    NUM_WORKERS = 1

    # [MODE]
    MODE_SYNCHRONIZATION = True
    MODE_GRADIENTS_UPDATE = True      # Distributed
    MODE_PARAMETERS_TRANSFER = False    # Transfer

    # [1. ENVIRONMENTS]
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_MATLAB_V0

    # [2. DEEP_LEARNING_MODELS]
    DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_ACTOR_CRITIC_MLP

    # [3. ALGORITHMS]
    RL_ALGORITHM = RLAlgorithmName.D4PG_FAST_V0

    # [4. OPTIMIZER]
    OPTIMIZER = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 1500
    STOP_PATIENCE_COUNT = 10
    AVG_EPISODE_SIZE_FOR_STAT = 10

    REPLAY_BUFFER_SIZE = 1000000
    MAX_GLOBAL_STEP = 5000000
    LEARNING_RATE = 0.002
    ACTOR_LEARNING_RATE = 0.0002
    TRAIN_STEP_FREQ = 1
    GAMMA = 0.99
    BATCH_SIZE = 64

    DRAW_VIZ = False
    N_STEP = 4
    OMEGA = False

    EPSILON_INIT = 0.9
    EPSILON_MIN = 0.001
    EPSILON_MIN_STEP = 1000000

    EPSILON_SWING_UP_MIN_STEP = 500000
    EPSILON_BALANCING_MIN_STEP = 200000

    CLIP_GRAD = 0.1

    RNN_STEP_LENGTH = 2
    PER = False

    ENV_RENDER = False

    ACTION_SCALE = 0.05

    ENV_RESET = False

    V_MAX = 1200
    V_MIN = -1
    N_ATOMS = 251

    SAVE_AT_MAX_GLOBAL_STEPS = True