# https://github.com/Huffon/pytorch-transformer-kor-eng
# -*- coding: utf-8 -*-
"""transformer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14V0xmynwaN3RDTeb2TEjJBdFm2dFZiO0

- https://github.com/Huffon/pytorch-transformer-kor-eng
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install soynlp
# !pip install spacy==2.3.2
# !pip install torchtext==0.8.0
# !python -m spacy download en

import torch
import torch.nn as nn
import numpy as np
import os.path
import re
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import time

import torch.nn.functional as F

import torchtext
from torchtext import data as ttd
from soynlp.word import WordExtractor
from soynlp.tokenizer import LTokenizer

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(torch.__version__)
print(torchtext.__version__)

"""# 파라미터 정의"""

RANDOM_SEED = 42
CLIP = 1

BATCH_SIZE = 128
NUM_EPOCH = 70
WARM_STEPS = 4000

MODEL_DIM = 512
FEED_FORWARD_DIM = 2048
N_LAYER = 6
N_HEAD = 8
MAX_LEN = 64
DROPOUT = 0.1
assert MODEL_DIM % N_HEAD == 0

SAVE_MODE = "model.pt"
MAKE_ALL_DATA_DONE = False

saved_data_file_list = [
    os.path.exists('kor_field.pickle'),
    os.path.exists('eng_field.pickle'),
    os.path.exists('train_data.pickle'),
    os.path.exists('valid_data.pickle'),
    os.path.exists('test_data.pickle')
]

if all(saved_data_file_list):
    MAKE_ALL_DATA_DONE = True

    with open('kor_field.pickle', 'rb') as f:
        kor_field = pickle.load(f)

    with open('eng_field.pickle', 'rb') as f:
        eng_field = pickle.load(f)

    with open('train_data.pickle', 'rb') as f:
        train_data = pickle.load(f)

    with open('valid_data.pickle', 'rb') as f:
        valid_data = pickle.load(f)

    with open('test_data.pickle', 'rb') as f:
        test_data = pickle.load(f)




"""# 데이터 전처리

- 한국어 Tokenizer 구성 
  - soynlp 기반 토크나이저 구성
"""


# https://lovit.github.io/nlp/2018/04/09/cohesion_ltokenizer/
# Cohesion episode_reward + L-Tokenizer. 띄어쓰기가 잘 되어있는 한국어 문서를 위한 unsupervised tokenizer 생성
def build_korean_tokenizer():
    """
    Train soynlp tokenizer which will be used to tokenize Korean input sentence
    """
    print(f'Now building soy-nlp tokenizer . . .')

    train_file = 'https://github.com/Huffon/pytorch-transformer-kor-eng/raw/master/data/corpus.csv'
    df = pd.read_csv(train_file, encoding='utf-8')

    # if encounters non-text row, we should skip it
    kor_lines = [
        row.korean for _, row in df.iterrows() if type(row.korean) == str
    ]

    word_extractor = WordExtractor(min_frequency=5)
    word_extractor.train(kor_lines)

    word_scores = word_extractor.extract()
    cohesion_scores = {
        word: episode_reward.cohesion_forward for word, episode_reward in word_scores.items()
    }

    tokenizer = LTokenizer(scores=cohesion_scores)

    return tokenizer


def clean_text(text):
    """
    텍스트를 정규화하기 위하여 입력된 text로 부터 스페셜 문자 제거
    Args:
        text: (string) text string which may contain special character
    Returns:
        normalized sentence
    """
    text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`…》]', '', text)
    return text


def convert_to_dataset(data, kor_field, eng_field):
    """
    Pre-process input DataFrame and convert pandas DataFrame to torchtext Dataset.
    Args:
        data: (DataFrame) pandas DataFrame to be converted into torchtext Dataset
        kor_field: torchtext Field containing Korean sentence
        eng_field: torchtext Field containing English sentence
    Returns:
        (Dataset) torchtext Dataset containing 'kor' and 'eng' Fields
    """
    # drop missing values not containing str value from DataFrame
    missing_rows = [idx for idx, row in data.iterrows()
                    if type(row.korean) != str or type(row.english) != str]

    data = data.drop(missing_rows)

    # convert each row of DataFrame to torchtext 'Example' containing 'kor' and 'eng' Fields
    list_of_examples = [
        torchtext.data.Example.fromlist(
            row.apply(lambda x: clean_text(x)).tolist(),
            fields=[('kor', kor_field), ('eng', eng_field)]
        ) for _, row in data.iterrows()
    ]

    # construct torchtext 'Dataset' using torchtext 'Example' list
    dataset = torchtext.data.Dataset(
        examples=list_of_examples,
        fields=[('kor', kor_field), ('eng', eng_field)]
    )

    return dataset


"""- TorchText Field
  - Tensor로 표현되어질 수 있는 공통의 텍스트 처리 데이터타입 모델
  - vocab 객체: 관리중인 단어 집합
    - 관리중인 단어 각각에 대해 수치적 표현 관리
"""


# https://wikidocs.net/60314
def build_vocab(tokenizer, kor_vocab_size=55000, eng_vocab_size=30000):
    """
    Build vocab used to convert input sentence into word indices using soynlp and spacy tokenizer
    Args:
        kor_vocab: size of Korean vocabulary
        eng_vocab: size of English vocabulary
    """

    # include lengths of the source sentences to use pack pad sequence
    kor_field = ttd.Field(
        tokenize=tokenizer.tokenize,
        lower=True,
        batch_first=True
    )

    eng_field = ttd.Field(
        tokenize='spacy',
        init_token='<sos>',
        eos_token='<eos>',
        lower=True,
        batch_first=True
    )

    train_file = 'https://github.com/Huffon/pytorch-transformer-kor-eng/raw/master/data/train.csv'
    train_data = pd.read_csv(train_file, encoding='utf-8')
    train_data = convert_to_dataset(train_data, kor_field, eng_field)

    print(f'Build vocabulary using torchtext . . .')

    kor_field.build_vocab(train_data, max_size=kor_vocab_size)
    eng_field.build_vocab(train_data, max_size=eng_vocab_size)

    print(f'Unique tokens in Korean vocabulary: {len(kor_field.vocab)}')
    print(f'Unique tokens in English vocabulary: {len(eng_field.vocab)}')

    print(f'Most commonly used Korean words are as follows:')
    print(kor_field.vocab.freqs.most_common(20))

    print(f'Most commonly used English words are as follows:')
    print(eng_field.vocab.freqs.most_common(20))

    return kor_field, eng_field


"""# 훈련, 검증, 테스트 데이터 준비"""


def load_dataset(mode):
    """
    Load train, valid and test dataset as a pandas DataFrame
    Args:
        mode: (string) configuration mode used to which dataset to load
    Returns:
        (DataFrame) train, valid, test dataset converted to pandas DataFrame
    """
    print(f'Loading AI Hub Kor-Eng translation dataset and converting it to pandas DataFrame . . .')

    if mode == 'train':
        train_file = 'https://github.com/Huffon/pytorch-transformer-kor-eng/raw/master/data/train.csv'
        train_data = pd.read_csv(train_file, encoding='utf-8')

        valid_file = 'https://github.com/Huffon/pytorch-transformer-kor-eng/raw/master/data/valid.csv'
        valid_data = pd.read_csv(valid_file, encoding='utf-8')

        print(f'Number of training examples: {len(train_data)}')
        print(f'Number of validation examples: {len(valid_data)}')

        return train_data, valid_data

    else:
        test_file = 'https://github.com/Huffon/pytorch-transformer-kor-eng/raw/master/data/test.csv'
        test_data = pd.read_csv(test_file, encoding='utf-8')

        print(f'Number of testing examples: {len(test_data)}')

        return test_data


def make_iter(batch_size, mode, kor_field, eng_field, train_data=None, valid_data=None, test_data=None):
    """
    Convert pandas DataFrame to torchtext Dataset and make iterator which will be used to train and test the model
    Args:
        batch_size: (integer) batch size used to make iterators
        mode: (string) configuration mode used to which iterator to make
        train_data: (DataFrame) pandas DataFrame used to build train iterator
        valid_data: (DataFrame) pandas DataFrame used to build validation iterator
        test_data: (DataFrame) pandas DataFrame used to build test iterator
    Returns:
        (BucketIterator) train, valid, test iterator
    """
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # convert pandas DataFrame to torchtext dataset
    if mode == 'train':
        train_data = convert_to_dataset(train_data, kor_field, eng_field)
        valid_data = convert_to_dataset(valid_data, kor_field, eng_field)

        # make iterator using train and validation dataset
        print(f'Make Iterators for training . . .')
        train_iter, valid_iter = ttd.BucketIterator.splits(
            (train_data, valid_data),
            # the BucketIterator needs to be told what function it should use to group the data.
            # In our case, we sort dataset using text of example
            sort_key=lambda sent: len(sent.kor),
            # all of the tensors will be sorted by their length by below option
            sort_within_batch=True,
            batch_size=batch_size,
            device=device
        )
        return train_iter, valid_iter

    else:
        test_data = convert_to_dataset(test_data, kor_field, eng_field)

        # defines dummy list will be passed to the BucketIterator
        dummy = list()

        # make iterator using test dataset
        print(f'Make Iterators for testing . . .')
        test_iter, _ = ttd.BucketIterator.splits(
            (test_data, dummy),
            sort_key=lambda sent: len(sent.kor),
            sort_within_batch=True,
            batch_size=batch_size,
            device=device
        )

        return test_iter


if not MAKE_ALL_DATA_DONE:
    korean_tokenizer = build_korean_tokenizer()

    train_file = 'https://github.com/Huffon/pytorch-transformer-kor-eng/raw/master/data/train.csv'
    train_data = pd.read_csv(train_file, encoding='utf-8')
    print(train_data.head(10))

    kor_field, eng_field = build_vocab(
        korean_tokenizer,
        kor_vocab_size=55000,
        eng_vocab_size=30000
    )

    for idx, item in enumerate(kor_field.vocab.stoi.items()):
        if idx == 20:
            break
        print(item)

    for idx, item in enumerate(eng_field.vocab.stoi.items()):
        if idx == 20:
            break
        print(item)


if not MAKE_ALL_DATA_DONE:
    train_data, valid_data = load_dataset(mode="train")
    test_data = load_dataset(mode="test")


if not MAKE_ALL_DATA_DONE:
    with open('kor_field.pickle', 'wb') as f:
        pickle.dump(kor_field, f)

    with open('eng_field.pickle', 'wb') as f:
        pickle.dump(eng_field, f)

    with open('train_data.pickle', 'wb') as f:
        pickle.dump(train_data, f)

    with open('valid_data.pickle', 'wb') as f:
        pickle.dump(valid_data, f)

    with open('test_data.pickle', 'wb') as f:
        pickle.dump(test_data, f)


train_iter, valid_iter = make_iter(
    batch_size=BATCH_SIZE,
    mode="train",
    kor_field=kor_field,
    eng_field=eng_field,
    train_data=train_data,
    valid_data=valid_data
)

test_iter = make_iter(
    batch_size=BATCH_SIZE,
    mode="test",
    kor_field=kor_field,
    eng_field=eng_field,
    test_data=test_data
)

INPUT_DIM = len(kor_field.vocab)
OUTPUT_DIM = len(eng_field.vocab)
SOS_IDX = eng_field.vocab.stoi['<sos>']
EOS_IDX = eng_field.vocab.stoi['<eos>']
PAD_IDX = eng_field.vocab.stoi['<pad>']

# for batch in train_iter:
#     # For each batch, first zero the gradients
#     source = batch.kor      # source = [batch_size, 9],  [batch_size, 8]
#     target = batch.eng      # target = [batch_size, 27], [batch_size, 21]

print("\n\n\n\n\n\n\n")


"""# 모델 구성시 필요한 유틸리티 함수 정의"""


def create_look_ahead_mask(target):
    """
    if target length is 5 and diagonal is 1, this function returns
        [[0, 1, 1, 1, 1],
         [0, 0, 1, 1, 1],
         [0, 0, 0, 1, 1],
         [0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0]]

    :param target: [batch size, target length]
    :return: look_ahead_mask
        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]
    """
    batch_size, target_length = target.size()

    # torch.triu returns the upper triangular part of a matrix based on user defined diagonal
    look_ahead_mask = torch.triu(
        torch.ones(target_length, target_length), diagonal=1
    ).bool().to(device)
    # look_ahead_mask = (target length, target length)

    # repeat look_ahead_mask 'batch size' times to cover all data instances in the batch
    # A.unsqueeze(0) turns A from an [M, N] to [1, M, N]
    # and .repeat(K, 1, 1) repeats the tensor K times along the first dimension.
    look_ahead_mask = look_ahead_mask.unsqueeze(0).repeat(batch_size, 1, 1)
    # look_ahead_mask = [batch size, target length, target length]

    return look_ahead_mask


target = torch.Tensor(
    [[1, 2, 3, 4],
     [10, 20, 30, 40],
     [4, 3, 2, 1]]
).to(device)

look_ahead_mask = create_look_ahead_mask(target)
print(look_ahead_mask)


def create_padding_mask(source):
    """
    create masking tensor for encoder's self attention
    if sentence is [2, 193, 9, 27, 10003, 1, 1, 1, 3] and 2 denotes <sos>, 3 denotes <eos> and 1 denotes <pad>
    masking tensor will be [False, False, False, False, False, True, True, True, False]
    :param source: [batch size, source length]
    :return: source mask
    """
    source_length = source.shape[1]

    # create boolean tensors which will be used to mask padding tokens of both source and target sentence
    padding_mask = (source == PAD_IDX)
    # padding_mask = (batch size, source length)

    # repeat sentence masking tensors 'sentence length' times
    # A.unsqueeze(1) turns A from an [M, N] to [M, 1, N]
    # and .repeat(1, K, 1) repeats the tensor K times along the second dimension.
    padding_mask = padding_mask.unsqueeze(1).repeat(1, source_length, 1)
    # padding_mask = (batch size, source length, source length)

    return padding_mask


source = torch.Tensor(
    [[1, 2, 3],
     [10, 20, 30],
     [3, 2, 1]]
).to(device)

padding_mask = create_padding_mask(target)
print(padding_mask)


def create_target_mask(source, target):
    """
    create masking tensor for decoder's self attention and decoder's attention on the output of encoder
    if sentence is [2, 193, 9, 27, 10003, 1, 1, 1, 3] and 2 denotes <sos>, 3 denotes <eos> and 1 denotes <pad>
    masking tensor will be [False, False, False, False, False, True, True, True, False]
    :param source: [batch size, source length]
    :param target: [batch size, target length]
    :return:
    """
    target_length = target.shape[1]

    look_ahead_mask = create_look_ahead_mask(target)
    # look_ahead_mask = (batch size, target length, target length)

    source_mask = (source == PAD_IDX)
    # source_mask = (batch size, source length)

    target_mask = (target == PAD_IDX)
    # target_mask = (batch size, target length)

    # repeat sentence masking tensors 'sentence length' times
    encoder_decoder_mask = source_mask.unsqueeze(1).repeat(1, target_length, 1)
    # encoder_decoder_mask = [batch size, target length, source length]

    target_mask = target_mask.unsqueeze(1).repeat(1, target_length, 1)
    # target_mask = [batch size, target length, target length]

    # combine <pad> token masking tensor and subsequent masking tensor for decoder's self attention
    target_mask = target_mask | look_ahead_mask
    # target_mask = [batch size, target length, target length]

    return target_mask, encoder_decoder_mask


source = torch.Tensor(
    [[1, 2, 3],
     [10, 20, 30],
     [3, 2, 1]]
).to(device)

target = torch.Tensor(
    [[1, 2, 3, 4],
     [10, 20, 30, 40],
     [4, 3, 2, 1]]
).to(device)

target_mask, encoder_decoder_mask = create_target_mask(source, target)

print(target_mask)
print()
print(encoder_decoder_mask)


def create_position_vector(sentence):
    """
    create position vector which contains positional information
    0th position is used for pad index
    :param sentence: [batch size, sentence length]
    :return: [batch size, sentence length]
    """
    # sentence = [batch size, sentence length]
    batch_size, _ = sentence.size()
    position_vec = np.array(
        [(position + 1) if word != PAD_IDX else 0
         for row in range(batch_size)
         for position, word in enumerate(sentence[row])]
    )
    position_vec = position_vec.reshape(batch_size, -1)
    position_vec = torch.LongTensor(position_vec).to(device)
    return position_vec


sentence = torch.Tensor(
    [[1, 2, 3, 4],
     [10, 20, 30, 40]]
).to(device)

position_vector = create_position_vector(sentence)
print(position_vector)


def create_positional_encoding(max_len, model_dim):
    # PE(position, 2i)     = sin(position/10000 ** (2*i / model_dim))
    # PE(position, 2i + 1) = cos(position/10000 ** (2*i / model_dim))
    sinusoid_table = np.array(
        [position / np.power(10000, 2 * i / model_dim)
         for position in range(max_len)
         for i in range(model_dim)]
    )
    # sinusoid_table = [max len * model dim]

    sinusoid_table = sinusoid_table.reshape(max_len, -1)
    # sinusoid_table = [max len, model dim]

    sinusoid_table[:, 0::2] = np.sin(sinusoid_table[:, 0::2])  # calculate pe for even dimension
    sinusoid_table[:, 1::2] = np.cos(sinusoid_table[:, 1::2])  # calculate pe for odd dimension

    # convert numpy based sinusoid table to torch.tensor and repeat it 'batch size' times
    sinusoid_table = torch.FloatTensor(sinusoid_table).to(device)
    sinusoid_table[0] = 0.

    return sinusoid_table


sinusoid_table = create_positional_encoding(50, 512)

plt.figure(figsize=(30, 10))
plt.pcolormesh(sinusoid_table.cpu().numpy(), cmap='RdBu')
plt.xlabel('Depth')
plt.xlim((0, 512))
plt.ylabel('Position')
plt.colorbar()
plt.show()


def create_source_mask(source):
    """
    create masking tensor for encoder's self attention
    if sentence is [2, 193, 9, 27, 10003, 1, 1, 1, 3] and 2 denotes <sos>, 3 denotes <eos> and 1 denotes <pad>
    masking tensor will be [False, False, False, False, False, True, True, True, False]
    :param source: [batch size, source length]
    :return: source mask
    """
    source_length = source.shape[1]

    # create boolean tensors which will be used to mask padding tokens of both source and target sentence
    source_mask = (source == PAD_IDX)
    # source_mask = [batch size, source length]

    # repeat sentence masking tensors 'sentence length' times
    source_mask = source_mask.unsqueeze(1).repeat(1, source_length, 1)
    # source_mask = [batch size, source length, source length]

    return source_mask


"""# Attention 구성"""


class SelfAttention(nn.Module):
    def __init__(self):
        super(SelfAttention, self).__init__()
        self.model_dim = MODEL_DIM
        self.attention_dim = MODEL_DIM // N_HEAD

        self.q_w = nn.Linear(self.model_dim, self.attention_dim, bias=False)
        self.k_w = nn.Linear(self.model_dim, self.attention_dim, bias=False)
        self.v_w = nn.Linear(self.model_dim, self.attention_dim, bias=False)
        self.init_weight(self.q_w)
        self.init_weight(self.k_w)
        self.init_weight(self.v_w)

        self.dropout = nn.Dropout(DROPOUT)
        self.scale_factor = torch.sqrt(
            torch.FloatTensor([self.attention_dim])
        ).to(device)

    @staticmethod
    def init_weight(layer):
        nn.init.xavier_uniform_(layer.weight)
        if layer.bias is not None:
            nn.init.constant_(layer.bias, 0)

    def forward(self, query, key, value, mask=None):
        # query, key, value = [batch size, sentence length, model dim]

        # create Q, K, V matrices using identical input sentence to calculate self-attention episode_reward
        q = self.q_w(query)
        k = self.k_w(key)
        v = self.v_w(value)
        # q, k, v = [batch size, sentence length, attention dim]

        # Performs a batch matrix-matrix product of matrices stored in input and mat.
        self_attention = torch.bmm(q, k.permute(0, 2, 1))
        self_attention = self_attention / self.scale_factor
        # self_attention = [batch size, sentence length, sentence length]

        if mask is not None:
            self_attention = self_attention.masked_fill(mask, -np.inf)

        # normalize self attention episode_reward by applying soft max function on each row
        attention_score = F.softmax(self_attention, dim=-1)
        norm_attention_score = self.dropout(attention_score)
        # attention_score = [batch size, sentence length, sentence length]

        # compute "weighted" value matrix using self attention episode_reward and V matrix
        weighted_v = torch.bmm(norm_attention_score, v)
        # weighted_v = [batch size, sentence length, attention dim]

        return self.dropout(weighted_v), attention_score


class MultiHeadAttention(nn.Module):
    def __init__(self):
        super(MultiHeadAttention, self).__init__()

        self.attentions = nn.ModuleList(
            [SelfAttention() for _ in range(N_HEAD)]
        )
        self.o_w = nn.Linear(MODEL_DIM, MODEL_DIM, bias=False)
        self.init_weight(self.o_w)
        self.dropout = nn.Dropout(DROPOUT)

    @staticmethod
    def init_weight(layer):
        nn.init.xavier_uniform_(layer.weight)
        if layer.bias is not None:
            nn.init.constant_(layer.bias, 0)

    def forward(self, query, key, value, mask=None):
        # query, key, value = [batch size, sentence length, model dim]

        self_attentions = [
            attention(query, key, value, mask) for attention in self.attentions
        ]
        # self_attentions = [batch size, sentence length, attention dim] * num head
        weighted_vs = [weighted_v[0] for weighted_v in self_attentions]
        attentions = [weighted_v[1] for weighted_v in self_attentions]

        weighted_v = torch.cat(weighted_vs, dim=-1)
        # weighted_v = [batch size, sentence length, model dim]

        output = self.dropout(self.o_w(weighted_v))
        # output = [batch size, sentence length, model dim]

        return output, attentions


"""# Encoder 구성"""


class EncoderLayer(nn.Module):
    def __init__(self):
        super(EncoderLayer, self).__init__()
        self.layer_norm = nn.LayerNorm(MODEL_DIM, eps=1e-6)
        self.self_attention = MultiHeadAttention()
        self.position_wise_ffn = PositionWiseFeedForward()

    def forward(self, source, source_mask):
        # source          = [batch size, source length, model dim]
        # source_mask     = [batch size, source length, source length]

        # Original Implementation: LayerNorm(x + SubLayer(x))
        # -> Updated Implementation: x + SubLayer(LayerNorm(x))
        normalized_source = self.layer_norm(source)
        # normalized_source = [batch size, source length, model dim]

        # Residual Connection
        output = source + self.self_attention(normalized_source, normalized_source, normalized_source, source_mask)[0]
        # output = [batch size, source length, model dim]

        normalized_output = self.layer_norm(output)

        # Residual Connection
        output = output + self.position_wise_ffn(normalized_output)
        # output = [batch size, source length, model dim]

        return output


class PositionWiseFeedForward(nn.Module):
    def __init__(self):
        super(PositionWiseFeedForward, self).__init__()
        # nn.Conv1d takes input whose size is (N, C): N is a batch size, C denotes a number of channels
        self.conv1 = nn.Conv1d(
            MODEL_DIM, FEED_FORWARD_DIM, kernel_size=1
        )
        self.conv2 = nn.Conv1d(
            FEED_FORWARD_DIM, MODEL_DIM, kernel_size=1
        )
        self.init_weight(self.conv1)
        self.init_weight(self.conv2)
        self.dropout = nn.Dropout(DROPOUT)

    @staticmethod
    def init_weight(layer):
        nn.init.xavier_uniform_(layer.weight)
        if layer.bias is not None:
            nn.init.constant_(layer.bias, 0)

    def forward(self, x):
        # x = [batch size, sentence length, model dim]

        # permute x's indices to apply nn.Conv1d on input 'x'
        x = x.permute(0, 2, 1)  # x = [batch size, model dim, sentence length]
        output = self.dropout(F.relu(self.conv1(x)))  # output = [batch size, feed forward dim, sentence length)
        output = self.conv2(output)  # output = [batch size, model dim, sentence length)

        # permute again to restore output's original indices
        output = output.permute(0, 2, 1)  # output = [batch size, sentence length, model dim]
        return self.dropout(output)


class Encoder(nn.Module):
    def __init__(self):
        super(Encoder, self).__init__()
        self.token_embedding = nn.Embedding(
            num_embeddings=INPUT_DIM, embedding_dim=MODEL_DIM, padding_idx=PAD_IDX
        )
        nn.init.normal_(
            self.token_embedding.weight, mean=0, std=MODEL_DIM ** -0.5
        )
        self.embedding_scale = MODEL_DIM ** 0.5
        self.pos_embedding = nn.Embedding.from_pretrained(
            create_positional_encoding(MAX_LEN + 1, MODEL_DIM), freeze=True
        )
        self.encoder_layers = nn.ModuleList(
            [EncoderLayer() for _ in range(N_LAYER)]
        )
        self.dropout = nn.Dropout(DROPOUT)
        self.layer_norm = nn.LayerNorm(MODEL_DIM, eps=1e-6)

    def forward(self, source):
        # source = [batch size, source length]
        source_mask = create_source_mask(source)  # [batch size, source length, source length]

        source_pos = create_position_vector(source)  # [batch size, source length]
        source = self.token_embedding(source) * self.embedding_scale
        source = self.dropout(source + self.pos_embedding(source_pos))
        # source = [batch size, source length, model dim]

        for encoder_layer in self.encoder_layers:
            source = encoder_layer(source, source_mask)
        # source = [batch size, source length, model dim]

        return self.layer_norm(source)


"""# Decoder 구성"""


class DecoderLayer(nn.Module):
    def __init__(self):
        super(DecoderLayer, self).__init__()
        self.layer_norm = nn.LayerNorm(MODEL_DIM, eps=1e-6)
        self.self_attention = MultiHeadAttention()
        self.encoder_attention = MultiHeadAttention()
        self.position_wise_ffn = PositionWiseFeedForward()

    def forward(self, target, encoder_output, target_mask, encoder_decoder_mask):
        # target          = [batch size, target length, model dim]
        # encoder_output  = [batch size, source length, model dim]
        # target_mask     = [batch size, target length, target length]
        # encoder_decoder_mask    = [batch size, target length, source length]

        # Original Implementation: LayerNorm(x + SubLayer(x)) -> Updated Implementation: x + SubLayer(LayerNorm(x))
        norm_target = self.layer_norm(target)
        output = target + self.self_attention(norm_target, norm_target, norm_target, target_mask)[0]

        # In Decoder stack, query is the output from below layer and key & value are the output from the Encoder
        norm_output = self.layer_norm(output)
        sub_layer, encoder_decoder_attention_map = self.encoder_attention(norm_output, encoder_output, encoder_output, encoder_decoder_mask)
        output = output + sub_layer

        norm_output = self.layer_norm(output)
        output = output + self.position_wise_ffn(norm_output)
        # output = [batch size, target length, model dim]

        return output, encoder_decoder_attention_map


class Decoder(nn.Module):
    def __init__(self):
        super(Decoder, self).__init__()
        self.token_embedding = nn.Embedding(
            num_embeddings=OUTPUT_DIM, embedding_dim=MODEL_DIM, padding_idx=PAD_IDX
        )
        nn.init.normal_(
            self.token_embedding.weight, mean=0, std=MODEL_DIM ** -0.5
        )
        self.embedding_scale = MODEL_DIM ** 0.5
        self.pos_embedding = nn.Embedding.from_pretrained(
            create_positional_encoding(MAX_LEN + 1, MODEL_DIM), freeze=True
        )
        self.decoder_layers = nn.ModuleList(
            [DecoderLayer() for _ in range(N_LAYER)]
        )
        self.dropout = nn.Dropout(DROPOUT)
        self.layer_norm = nn.LayerNorm(MODEL_DIM, eps=1e-6)

    def forward(self, target, source, encoder_output):
        # target              = [batch size, target length]
        # source              = [batch size, source length]
        # encoder_output      = [batch size, source length, model dim]

        target_mask, encoder_decoder_mask = create_target_mask(source, target)
        # target_mask           = [batch size, target length, target length]
        # encoder_decoder_mask = [batch size, target length, source length]

        target_pos = create_position_vector(target)  # target_pos = [batch size, target length]
        target = self.token_embedding(target) * self.embedding_scale
        target = self.dropout(target + self.pos_embedding(target_pos))
        # target = [batch size, target length, model dim]

        for decoder_layer in self.decoder_layers:
            target, encoder_decoder_attention_map = decoder_layer(
                target, encoder_output, target_mask, encoder_decoder_mask
            )
        # target = [batch size, target length, model dim]

        target = self.layer_norm(target)
        output = torch.matmul(target, self.token_embedding.weight.transpose(0, 1))
        # output = [batch size, target length, output dim]
        return output, encoder_decoder_attention_map


"""# Transformer 구성"""


class Transformer(nn.Module):
    def __init__(self):
        super(Transformer, self).__init__()
        self.encoder = Encoder()
        self.decoder = Decoder()

    def forward(self, source, target):
        # source = [batch size, source length]
        # target = [batch size, target length]

        # [batch size, source length, model dim]
        encoder_output = self.encoder(source)

        # [batch size, target length, output dim]
        output, encoder_decoder_attention_map = self.decoder(target, source, encoder_output)

        return output, encoder_decoder_attention_map

    def count_params(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


class ScheduledAdam():
    def __init__(self, optimizer, model_dim, warm_steps):
        self.init_lr = np.power(model_dim, -0.5)
        self.optimizer = optimizer
        self.current_steps = 0
        self.warm_steps = warm_steps

    def step(self):
        # Update learning rate using current step information
        self.current_steps += 1
        lr = self.init_lr * self.get_scale()

        for p in self.optimizer.param_groups:
            p['lr'] = lr

        self.optimizer.step()

    def zero_grad(self):
        self.optimizer.zero_grad()

    def get_scale(self):
        return np.min([
            np.power(self.current_steps, -0.5),
            self.current_steps * np.power(self.warm_steps, -0.5)
        ])


class Trainer:
    def __init__(self):
        self.model = Transformer()
        self.model.to(device)

        # Scheduling Optimzer
        self.optimizer = ScheduledAdam(
            torch.optim.Adam(
                self.model.parameters(),
                betas=(0.9, 0.98),
                eps=1e-9
            ),
            model_dim=MODEL_DIM,
            warm_steps=WARM_STEPS
        )

        self.criterion = nn.CrossEntropyLoss(ignore_index=PAD_IDX)
        self.criterion.to(device)

    def train(self):
        print(self.model)
        print(f'The model has {self.model.count_params():,} trainable parameters')
        best_valid_loss = float('inf')

        for epoch in range(NUM_EPOCH):
            self.model.train()
            epoch_loss = 0
            start_time = time.time()

            for batch in train_iter:
                # For each batch, first zero the gradients
                self.optimizer.zero_grad()
                source = batch.kor      # source = [batch_size, 9],  [batch_size, 8]
                target = batch.eng      # target = [batch_size, 27], [batch_size, 21]

                # target sentence consists of <sos> and following tokens (except the <eos> token)
                output, encoder_decoder_attention_map = self.model(source, target[:, :-1])

                # ground truth sentence consists of tokens and <eos> token (except the <sos> token)
                # contiguous: it will change the data in memory so that the map from indices to memory location is the canonical one
                output = output.contiguous().view(-1, output.shape[-1])
                target = target[:, 1:].contiguous().view(-1)

                # output = [(batch size * target length - 1), output dim]
                # target = [(batch size * target length - 1)]
                loss = self.criterion(output, target)
                loss.backward()

                # clip the gradients to prevent the model from exploding gradient
                torch.nn.utils.clip_grad_norm_(self.model.parameters(), CLIP)

                self.optimizer.step()

                # 'item' method is used to extract a scalar from a tensor which only contains a single value.
                epoch_loss += loss.item()

            train_loss = epoch_loss / len(train_iter)
            valid_loss = self.evaluate()

            end_time = time.time()
            epoch_mins, epoch_secs = epoch_time(start_time, end_time)

            if valid_loss < best_valid_loss:
                best_valid_loss = valid_loss
                torch.save(self.model.state_dict(), SAVE_MODE)

            print(f'Epoch: {epoch + 1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
            print(f'\tTrain Loss: {train_loss:.3f} | Val. Loss: {valid_loss:.3f}')

    def evaluate(self):
        self.model.eval()
        epoch_loss = 0

        with torch.no_grad():
            for batch in valid_iter:
                source = batch.kor
                target = batch.eng

                output = self.model(source, target[:, :-1])[0]

                output = output.contiguous().view(-1, output.shape[-1])
                target = target[:, 1:].contiguous().view(-1)

                loss = self.criterion(output, target)

                epoch_loss += loss.item()

        return epoch_loss / len(valid_iter)


def epoch_time(start_time, end_time):
    """
    Calculate the time spent to train one epoch
    Args:
        start_time: (float) training start time
        end_time: (float) training end time
    Returns:
        (int) elapsed_mins and elapsed_sec spent for one epoch
    """
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))

    return elapsed_mins, elapsed_secs


def display_attention(candidate, translation, attention):
    """
    displays the model's attention over the source sentence for each target token generated.
    Args:
        candidate: (list) tokenized source tokens
        translation: (list) predicted target translation tokens
        attention: a tensor containing attentions scores
    Returns:
    """
    # attention = [target length, source length]

    attention = attention.cpu().detach().numpy()
    # attention = [target length, source length]

    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(111)

    ax.matshow(attention, cmap='bone')
    ax.tick_params(labelsize=15)
    ax.set_xticklabels([''] + [t.lower() for t in candidate], rotation=45)
    ax.set_yticklabels([''] + translation)

    ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(1))

    plt.show()
    plt.close()


if __name__ == '__main__':
    print("TRAIN Started!!!")

    trainer = Trainer()
    trainer.train()


class Tester:
    def __init__(self):
        self.model = Transformer()
        self.model.to(device)

        self.criterion = nn.CrossEntropyLoss(ignore_index=PAD_IDX)
        self.criterion.to(device)

    def inference(self):
        self.model.load_state_dict(torch.load(SAVE_MODE))
        self.model.eval()
        epoch_loss = 0

        with torch.no_grad():
            for batch in test_iter:
                source = batch.kor
                target = batch.eng

                output = self.model(source, target[:, :-1])[0]

                output = output.contiguous().view(-1, output.shape[-1])
                target = target[:, 1:].contiguous().view(-1)

                loss = self.criterion(output, target)

                epoch_loss += loss.item()

        test_loss = epoch_loss / len(test_iter)
        print(f'Test Loss: {test_loss:.3f}')


if __name__ == '__main__':
    tester = Tester()
    tester.inference()

