# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quanser_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='quanser_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15quanser_service.proto\"A\n\x12QuanserStepRequest\x12\r\n\x05value\x18\x01 \x01(\x02\x12\x0c\n\x04info\x18\x02 \x01(\t\x12\x0e\n\x06pub_id\x18\x03 \x01(\x02\"3\n\x13QuanserResetRequest\x12\x0c\n\x04info\x18\x01 \x01(\t\x12\x0e\n\x06pub_id\x18\x02 \x01(\x02\"\xb8\x01\n\x14QuanserStateResponse\x12\x14\n\x0cmotor_radian\x18\x01 \x01(\x02\x12\x16\n\x0emotor_velocity\x18\x02 \x01(\x02\x12\x17\n\x0fpendulum_radian\x18\x03 \x01(\x02\x12\x19\n\x11pendulum_velocity\x18\x04 \x01(\x02\x12\x0e\n\x06pub_id\x18\x05 \x01(\x02\x12\x16\n\x0eis_motor_limit\x18\x06 \x01(\x08\x12\x16\n\x0ereset_complete\x18\x07 \x01(\x08\x32t\n\x04RDIP\x12\x36\n\x05reset\x12\x14.QuanserResetRequest\x1a\x15.QuanserStateResponse\"\x00\x12\x34\n\x04step\x12\x13.QuanserStepRequest\x1a\x15.QuanserStateResponse\"\x00\x62\x06proto3'
)




_QUANSERSTEPREQUEST = _descriptor.Descriptor(
  name='QuanserStepRequest',
  full_name='QuanserStepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='QuanserStepRequest.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='QuanserStepRequest.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pub_id', full_name='QuanserStepRequest.pub_id', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=90,
)


_QUANSERRESETREQUEST = _descriptor.Descriptor(
  name='QuanserResetRequest',
  full_name='QuanserResetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='QuanserResetRequest.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pub_id', full_name='QuanserResetRequest.pub_id', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=143,
)


_QUANSERSTATERESPONSE = _descriptor.Descriptor(
  name='QuanserStateResponse',
  full_name='QuanserStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_radian', full_name='QuanserStateResponse.motor_radian', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_velocity', full_name='QuanserStateResponse.motor_velocity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pendulum_radian', full_name='QuanserStateResponse.pendulum_radian', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pendulum_velocity', full_name='QuanserStateResponse.pendulum_velocity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pub_id', full_name='QuanserStateResponse.pub_id', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_motor_limit', full_name='QuanserStateResponse.is_motor_limit', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reset_complete', full_name='QuanserStateResponse.reset_complete', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['QuanserStepRequest'] = _QUANSERSTEPREQUEST
DESCRIPTOR.message_types_by_name['QuanserResetRequest'] = _QUANSERRESETREQUEST
DESCRIPTOR.message_types_by_name['QuanserStateResponse'] = _QUANSERSTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuanserStepRequest = _reflection.GeneratedProtocolMessageType('QuanserStepRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUANSERSTEPREQUEST,
  '__module__' : 'quanser_service_pb2'
  # @@protoc_insertion_point(class_scope:QuanserStepRequest)
  })
_sym_db.RegisterMessage(QuanserStepRequest)

QuanserResetRequest = _reflection.GeneratedProtocolMessageType('QuanserResetRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUANSERRESETREQUEST,
  '__module__' : 'quanser_service_pb2'
  # @@protoc_insertion_point(class_scope:QuanserResetRequest)
  })
_sym_db.RegisterMessage(QuanserResetRequest)

QuanserStateResponse = _reflection.GeneratedProtocolMessageType('QuanserStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUANSERSTATERESPONSE,
  '__module__' : 'quanser_service_pb2'
  # @@protoc_insertion_point(class_scope:QuanserStateResponse)
  })
_sym_db.RegisterMessage(QuanserStateResponse)



_RDIP = _descriptor.ServiceDescriptor(
  name='RDIP',
  full_name='RDIP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=332,
  serialized_end=448,
  methods=[
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='RDIP.reset',
    index=0,
    containing_service=None,
    input_type=_QUANSERRESETREQUEST,
    output_type=_QUANSERSTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='step',
    full_name='RDIP.step',
    index=1,
    containing_service=None,
    input_type=_QUANSERSTEPREQUEST,
    output_type=_QUANSERSTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RDIP)

DESCRIPTOR.services_by_name['RDIP'] = _RDIP

# @@protoc_insertion_point(module_scope)
