from codes.a_config._rl_parameters.genetic_algorithm import GENETIC_NEURO_EVOLUTION_ALGORITHM


class MULTI_GENETIC_NEURO_EVOLUTION_ALGORITHM(GENETIC_NEURO_EVOLUTION_ALGORITHM):
    WORKERS_COUNT = 6
    MAX_SEED = 2**32 - 1
    NUM_SEEDS_PER_WORKER = 300
    POPULATION_SIZE = NUM_SEEDS_PER_WORKER * WORKERS_COUNT
