from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_KNAPSACK_DQN(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.KNAPSACK_V2
    RL_ALGORITHM = RLAlgorithmName.DQN_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_MLP

    STOP_MEAN_EPISODE_REWARD = 100
    REPLAY_BUFFER_SIZE = 50000
    TARGET_NET_SYNC_STEP_PERIOD = 100
    MAX_GLOBAL_STEP = 500000
    EPSILON_MIN_STEP = 100000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01
    LEARNING_RATE = 0.001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 2
    AVG_EPISODE_SIZE_FOR_STAT = 30
    DRAW_VIZ = True
    N_STEP = 1
    OMEGA = False
