from codes.a_config.a_basic_parameters.parameters_cartpole_a2c          import PARAMETERS_CARTPOLE_A2C
from codes.a_config.a_basic_parameters.parameters_cartpole_dqn          import PARAMETERS_CARTPOLE_DQN
from codes.a_config.a_basic_parameters.parameters_cartpole_pg           import PARAMETERS_CARTPOLE_PG
from codes.a_config.a_basic_parameters.parameters_cartpole_reinforce    import PARAMETERS_CARTPOLE_REINFORCE
from codes.a_config.a_basic_parameters.parameters_pendulum_a2c import PARAMETERS_PENDULUM_A2C
from codes.a_config.a_basic_parameters.parameters_pendulum_ddpg import PARAMETERS_PENDULUM_DDPG
from codes.a_config.a_basic_parameters.parameters_pendulum_d4pg import PARAMETERS_PENDULUM_D4PG
from codes.a_config.a_basic_parameters.parameters_pendulum_ppo import PARAMETERS_PENDULUM_PPO
from codes.a_config.a_basic_parameters.parameters_pendulum_td3 import PARAMETERS_PENDULUM_TD3
from codes.a_config.a_basic_parameters.parameters_cartpole_ppo import PARAMETERS_CARTPOLE_PPO
from codes.a_config.a_basic_parameters.parameters_lunar_lander_a2c import PARAMETERS_LUNAR_LANDER_A2C
from codes.a_config.a_basic_parameters.parameters_lunar_lander_ppo import PARAMETERS_LUNAR_LANDER_PPO
from codes.a_config.a_basic_parameters.parameters_lunar_lander_continuous_a2c import PARAMETERS_LUNAR_LANDER_CONTINUOUS_A2C
from codes.a_config.a_basic_parameters.parameters_lunar_lander_continuous_ppo import PARAMETERS_LUNAR_LANDER_CONTINUOUS_PPO
from codes.a_config.a_basic_parameters.parameters_lunar_lander_continuous_ddpg import PARAMETERS_LUNAR_LANDER_CONTINUOUS_DDPG
from codes.a_config.a_basic_parameters.parameters_lunar_lander_ga import PARAMETERS_LUNAR_LANDER_GA
from codes.a_config.a_basic_parameters.parameters_lunar_lander_multi_ga import PARAMETERS_LUNAR_LANDER_MULTI_GA
from codes.a_config.a_basic_parameters.parameters_cartpole_emaes    import PARAMETERS_CARTPOLE_EMAES
from codes.a_config.a_basic_parameters.parameters_cartpole_ga       import PARAMETERS_CARTPOLE_GA
from codes.a_config.a_basic_parameters.parameters_acrobot_dqn import PARAMETERS_ACROBOT_DQN
from codes.a_config.a_basic_parameters.parameters_mountain_car_dqn import PARAMETERS_MOUNTAIN_CAR_DQN

from codes.a_config.b_atari_parameters.parameters_atari_pong_a2c        import PARAMETERS_PONG_A2C
from codes.a_config.b_atari_parameters.parameters_atari_pong_dqn        import PARAMETERS_PONG_DQN
from codes.a_config.b_atari_parameters.parameters_atari_breakout_dqn    import PARAMETERS_BREAKOUT_DQN
from codes.a_config.b_atari_parameters.parameters_atari_kungfumaster_dqn import PARAMETERS_KUNGFU_MASTER_DQN
from codes.a_config.b_atari_parameters.parameters_atari_pong_ppo        import PARAMETERS_PONG_PPO
from codes.a_config.b_atari_parameters.parameters_atari_pong_a2c import PARAMETERS_PONG_A2C
from codes.a_config.b_atari_parameters.parameters_atari_pong_emaes import PARAMETERS_PONG_EMAES
from codes.a_config.b_atari_parameters.parameters_atari_pong_multi_ga import PARAMETERS_PONG_MULTI_GA
from codes.a_config.b_atari_parameters.parameters_atari_freeway_dqn import PARAMETERS_FREEWAY_DQN

from codes.a_config.c_pybullet_parameters.parameters_half_cheetah_ppo import PARAMETERS_HALF_CHEETAH_PPO
from codes.a_config.c_pybullet_parameters.parameters_ant_sac import PARAMETERS_ANT_SAC
from codes.a_config.c_pybullet_parameters.parameters_inverted_double_pendulum_bullet_ddpg import \
    PARAMETERS_INVERTED_DOUBLE_PENDULUM_BULLET_DDPG
from codes.a_config.c_pybullet_parameters.parameters_inverted_double_pendulum_bullet_ppo import \
    PARAMETERS_INVERTED_DOUBLE_PENDULUM_BULLET_PPO
from codes.a_config.c_pybullet_parameters.parameters_ant_ppo import PARAMETERS_ANT_PPO
from codes.a_config.c_pybullet_parameters.parameters_ant_ddpg import PARAMETERS_ANT_DDPG
from codes.a_config.c_pybullet_parameters.parameters_ant_a2c import PARAMETERS_ANT_A2C

from codes.a_config.d_matlab_parameters.parameters_matlab_pendulum_ppo import \
    PARAMETERS_PENDULUM_MATLAB_PPO
from codes.a_config.d_matlab_parameters.parameters_matlab_pendulum_dqn import PARAMETERS_PENDULUM_MATLAB_DQN
from codes.a_config.d_matlab_parameters.parameters_matlab_pendulum_ddpg import PARAMETERS_PENDULUM_MATLAB_DDPG
from .d_matlab_parameters.parameters_matlab_pendulum_td3 import PARAMETERS_PENDULUM_MATLAB_TD3

from codes.a_config.e_real_device.parameters_rip import PARAMETERS_RIP
from codes.a_config.e_real_device.parameters_double_rip_ddpg import PARAMETERS_DOUBLE_RIP
from codes.a_config.e_real_device.parameters_quanser_rip_ddpg import PARAMETERS_QUANSER_RIP_DDPG

from codes.a_config.f_trade_parameters.parameters_trade_moc_one_hour_dqn import PARAMETERS_TRADE_MOC_ONE_HOUR_DQN

from codes.a_config.federated_parameters.parameters_federated_matlab_rip_ddpg   import PARAMETERS_FEDERATED_MATLAB_RIP_DDPG
from codes.a_config.federated_parameters.parameters_federated_pendulum_ddpg     import PARAMETERS_FEDERATED_PENDULUM_DDPG

from codes.a_config.or_parameters.parameters_fast_rl_knapsack_dqn import PARAMETERS_KNAPSACK_DQN
from codes.a_config.or_parameters.parameters_fast_rl_tsp_dqn import PARAMETERS_TSP_DQN

from codes.a_config.federated_parameters.parameters_federated_cartpole_ppo_mlp import PARAMETERS_FEDERATED_CARTPOLE_PPO_MLP

from codes.e_utils.names import OSName, EnvironmentName, RLAlgorithmName
from codes.e_utils.names import ModelSaveMode
