from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PENDULUM_DDPG(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_V0
    RL_ALGORITHM = RLAlgorithmName.DDPG_FAST_V0
    # DEEP_LEARNING_MODEL = DeepLearningModelName.DDPG_MLP
    DEEP_LEARNING_MODEL = DeepLearningModelName.DDPG_GRU
    #DEEP_LEARNING_MODEL = DeepLearningModelName.DDPG_GRU_ATTENTION

    STOP_MEAN_EPISODE_REWARD = -100
    REPLAY_BUFFER_SIZE = 500000
    MAX_GLOBAL_STEPS = 500000
    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.0001
    TRAIN_STEP_FREQ = 1
    GAMMA = 0.99
    BATCH_SIZE = 64
    AVG_EPISODE_SIZE_FOR_STAT = 100
    MODEL_SAVE_STEP_PERIOD = 100000
    MIN_REPLAY_SIZE_FOR_TRAIN = 500
    DRAW_VIZ = False
    N_STEP = 4
    OMEGA = False

    EPSILON_INIT = 0.9
    EPSILON_MIN = 0.001
    EPSILON_MIN_STEP = 100000

    CUDA = False

    CLIP_GRAD = 0.1

    RNN_STEP_LENGTH = 2
