from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PENDULUM_A2C_CONTINUOUS_ACTION(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_V0
    RL_ALGORITHM = RLAlgorithmName.A2C_CONTINUOUS_ACTION_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.ACTOR_CRITIC_MLP

    STOP_MEAN_EPISODE_REWARD = 195.0
    STOP_CONDITION_CONTINUOUS_EPISODE = 10
    REPLAY_BUFFER_SIZE = 50000
    MAX_GLOBAL_STEP = 100000
    LEARNING_RATE = 0.001
    GAMMA = 0.99
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 100
    MODEL_SAVE_STEP_PERIOD = 1000
    DRAW_VIZ = True
    N_STEP = 4
    OMEGA = False

    CUDA = False

    CLIP_GRAD = 0.1
