from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PENDULUM_MATLAB_DQN(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_MATLAB_V0
    RL_ALGORITHM = RLAlgorithmName.DQN_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.Dueling_DQN_MLP
    REPLAY_BUFFER = ReplayBufferName.PRIORITIZED_REPLAY_BUFFER

    STOP_MEAN_EPISODE_REWARD = 20000
    REPLAY_BUFFER_SIZE = 50000
    MIN_REPLAY_SIZE_FOR_TRAIN = 100
    TARGET_NET_SYNC_STEP_PERIOD = 100
    MAX_GLOBAL_STEPS = 20000
    EPSILON_MIN_STEP = 5000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01
    LEARNING_RATE = 0.001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 2
    AVG_EPISODE_SIZE_FOR_STAT = 30
    MODEL_SAVE_STEP_PERIOD = 1000
    DRAW_VIZ = 1
    N_STEP = 1
    OMEGA = False

    CUDA = False