from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_INVADERS_DQN(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PONG_NO_FRAME_SKIP_V4
    RL_ALGORITHM = RLAlgorithmName.DQN_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.Dueling_DQN_CNN
    REPLAY_BUFFER = ReplayBufferName.PRIORITIZED_REPLAY_BUFFER

    STOP_MEAN_EPISODE_REWARD = 18.0
    REPLAY_BUFFER_SIZE = 100000
    TRAIN_FOR_MIN_REPLAY_SIZE = 10000
    TARGET_NET_SYNC_STEPS = 1000
    EPSILON_MIN_STEPS = 100000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.02
    LEARNING_RATE = 0.0001
    GAMMA = 0.99
    MAX_GLOBAL_STEPS = 1000000
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 4