from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PENDULUM_MATLAB_DDPG(PARAMETERS_GENERAL):
    CH = False
    TEAMVIEWER = False

    ENV_RESET = True

    ENVIRONMENT_ID = "MatlabRotaryInvertedPendulumEnv"
    RL_ALGORITHM = RLAlgorithmName.DDPG_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DDPG_MLP
    #DEEP_LEARNING_MODEL = DeepLearningModelName.DDPG_GRU

    STOP_MEAN_EPISODE_REWARD = 1000000
    REPLAY_BUFFER_SIZE = 300000
    MAX_GLOBAL_STEPS = 1000000
    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.0001
    TRAIN_STEP_FREQ = 1
    GAMMA = 0.95
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 100
    MODEL_SAVE_STEP_PERIOD = 10000
    MIN_REPLAY_SIZE_FOR_TRAIN = 32

    EPSILON_INIT = 0.9
    EPSILON_MIN = 0.001
    EPSILON_MIN_STEP = 400000

    DRAW_VIZ = False
    DRAW_VIZ_PERIOD_STEPS = 10
    N_STEP = 4
    OMEGA = False

    CUDA = False

    CLIP_GRAD = 0.1

    LOAD_SAVED_ACTOR_MODEL = None
    LOAD_SAVED_CRITIC_MODEL = None

    RNN_STEP_LENGTH = 2