from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_MINITAUR_BULLET_A2C(PARAMETERS_GENERAL):
    ENVIRONMENT_ID      = EnvironmentName.MINITAUR_BULLET_V0
    RL_ALGORITHM        = RLAlgorithmName.A2C_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.ACTOR_CRITIC_MLP
    REPLAY_BUFFER       = ReplayBufferName.REPLAY_BUFFER
    OPTIMIZER           = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 500.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1000000
    MIN_REPLAY_SIZE_FOR_TRAIN = 50000
    TARGET_NET_SYNC_STEP_PERIOD = 10000
    MAX_GLOBAL_STEP = 10000000
    EPSILON_MIN_STEP = 1000000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.1
    LEARNING_RATE = 0.00025
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 4
    AVG_EPISODE_SIZE_FOR_STAT = 100
    MODEL_SAVE_STEP_PERIOD = 10000
    DRAW_VIZ = True
    N_STEP = 1
    OMEGA = False