from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PONG_DQN(PARAMETERS_GENERAL):
    RL_ALGORITHM = RLAlgorithmName.DQN_V1
    ENVIRONMENT_ID = EnvironmentName.PONGNOFRAMESKIP_V4
    DEEP_LEARNING_MODEL = DeepLearningModelName.DuelingDQNCNN

    STOP_MEAN_EPISODE_REWARD = 18.0
    REPLAY_BUFFER_SIZE = 100000
    TRAIN_FOR_MIN_REPLAY_SIZE = 10000
    TARGET_NET_SYNC_STEPS = 1000
    EPSILON_MIN_STEPS = 100000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.02
    LEARNING_RATE = 0.0001
    GAMMA = 0.99
    MAX_GLOBAL_STEPS = 1000000
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 4