from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PONG_DQN(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PONG_NO_FRAME_SKIP_V4
    RL_ALGORITHM = RLAlgorithmName.DQN_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_CNN
    REPLAY_BUFFER = ReplayBufferName.PRIORITIZED_REPLAY_BUFFER

    STOP_MEAN_EPISODE_REWARD = 18.0
    REPLAY_BUFFER_SIZE = 100000
    MIN_REPLAY_SIZE_FOR_TRAIN = 10000
    TARGET_NET_SYNC_STEP_PERIOD = 1000
    MAX_GLOBAL_STEPS = 1000000
    EPSILON_MIN_STEP = 100000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.02
    LEARNING_RATE = 0.0001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 4
    AVG_EPISODE_SIZE_FOR_STAT = 100
    MODEL_SAVE_STEP_PERIOD = 10000
    DRAW_VIZ = 1
    N_STEP = 1
    OMEGA = False

    CUDA = False