from config.names import *
from config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_TRADE_DQN(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.TRADE_V0
    RL_ALGORITHM = RLAlgorithmName.DQN_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_SMALL_CNN
    REPLAY_BUFFER = ReplayBufferName.PRIORITIZED_REPLAY_BUFFER

    STOP_MEAN_EPISODE_REWARD = 500.0
    STOP_CONDITION_CONTINUOUS_EPISODE = 10
    REPLAY_BUFFER_SIZE = 1000000
    MIN_REPLAY_SIZE_FOR_TRAIN = 50000
    TARGET_NET_SYNC_STEP_PERIOD = 10000
    MAX_GLOBAL_STEPS = 10000000
    EPSILON_MIN_STEP = 1000000
    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.001
    LEARNING_RATE = 0.0001
    GAMMA = 0.99
    BATCH_SIZE = 32
    TRAIN_STEP_FREQ = 8
    AVG_EPISODE_SIZE_FOR_STAT = 100
    MODEL_SAVE_STEP_PERIOD = 10000
    DATA_SAVE_STEP_PERIOD = 20000
    DRAW_VIZ = False
    N_STEP = 1
    OMEGA = False
    NEXT_STATE_IN_TRAJECTORY = False

    CUDA = False

    TEST_EPISODE_PERIOD = 5000