from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL

# https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_envs/minitaur/envs/minitaur_gym_env.py
class PARAMETERS_MINITAUR_BULLET_PPO(PARAMETERS_GENERAL):
    ENVIRONMENT_ID      = EnvironmentName.PYBULLET_MINITAUR_BULLET_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.STOCHASTIC_CONTINUOUS_ACTOR_CRITIC_MLP
    RL_ALGORITHM        = RLAlgorithmName.CONTINUOUS_PPO_V0
    OPTIMIZER           = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 10
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1000000
    TARGET_NET_SYNC_STEP_PERIOD = 10000
    MAX_GLOBAL_STEP = 10000000
    EPSILON_MIN_STEP = 2000000
    EPSILON_INIT = 0.9
    EPSILON_MIN = 0.001
    GAMMA = 0.99
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 50
    N_STEP = 1

    RNN_STEP_LENGTH = 2

    ACTION_SCALE = 1.0

    ## PPO
    PPO_GAE_LAMBDA = 0.95
    PPO_TRAJECTORY_SIZE = 2049
    PPO_TRAJECTORY_BATCH_SIZE = 32
    ACTOR_LEARNING_RATE = 0.0001
    LEARNING_RATE = 0.0003
    PPO_K_EPOCHS = 10
    PPO_EPSILON_CLIP = 0.2
    TRAIN_STEP_FREQ = 1