from codes.a_config._rl_parameters.on_policy.parameter_ppo import PARAMETERS_PPO
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_PENDULUM_MATLAB_PPO(PARAMETERS_GENERAL, PARAMETERS_PPO):
    ENV_RESET = False

    ENVIRONMENT_ID      = EnvironmentName.PENDULUM_MATLAB_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.STOCHASTIC_CONTINUOUS_ACTOR_CRITIC_MLP
    RL_ALGORITHM        = RLAlgorithmName.CONTINUOUS_PPO_V0
    OPTIMIZER           = OptimizerName.ADAM

    #DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_GRU

    STOP_MEAN_EPISODE_REWARD = 100000
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 300000
    MAX_GLOBAL_STEP = 1000000
    GAMMA = 0.999
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 50

    EPSILON_INIT = 0.9
    EPSILON_MIN = 0.001
    EPSILON_MIN_STEP = 500000

    OMEGA = False

    PER = False
    CLIP_GRAD = 0.1

    ACTION_SCALE = 3.0

    ## PPO
    PPO_GAE_LAMBDA = 0.95
    PPO_TRAJECTORY_SIZE = 2049
    PPO_TRAJECTORY_BATCH_SIZE = 32
    ACTOR_LEARNING_RATE = 0.0001
    LEARNING_RATE = 0.001
    PPO_K_EPOCHS = 10
    PPO_EPSILON_CLIP = 0.2
    TRAIN_STEP_FREQ = 1
    N_STEP = 1

    MODEL_SAVE_MODE = ModelSaveMode.FINAL_ONLY