from codes.a_config._rl_parameters.off_policy.parameter_ddpg import PARAMETERS_DDPG, DDPGTargetUpdateOnlyAfterEpisode, \
    DDPGActionType, DDPGActionSelectorType
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL, RIPEnvRewardType


class PARAMETERS_DOUBLE_PENDULUM_MATLAB_DDPG(PARAMETERS_GENERAL, PARAMETERS_DDPG):
    ENV_RESET = False
    ENV_RENDER = False

    ENVIRONMENT_ID = EnvironmentName.PENDULUM_MATLAB_DOUBLE_RIP_V0
    RL_ALGORITHM = RLAlgorithmName.DDPG_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_MLP

    TRAIN_STOP_EPISODE_REWARD = 40000  # MAX: 6.28 * 10000 = 62800 (Old), 90000 (New)
    TRAIN_STOP_EPISODE_REWARD_STD = 2000

    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 500000

    LEARNING_RATE = 0.002
    ACTOR_LEARNING_RATE = 0.0002

    TRAIN_STEP_FREQ = 4
    GAMMA = 0.999
    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50

    N_STEP = 2

    CLIP_GRAD = 0.1
    ACTION_SCALE = 2.5

    NOISE_ENABLED = True

    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = 100

    TYPE_OF_RIP_REWARD = RIPEnvRewardType.NEW  # "current_version"
    TYPE_OF_DDPG_ACTION = DDPGActionType.GAUSSIAN_NOISE_WITH_EPSILON
    TYPE_OF_DDPG_ACTION_SELECTOR = DDPGActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR

    MAX_EPISODE_STEP = 10000
    MAX_GLOBAL_STEP = 10000000
    EPSILON_MIN_STEP = 2000000
    MIN_REPLAY_SIZE_FOR_TRAIN = 500

    IGNORE_ARM_INFO = False
