from codes.a_config._rl_parameters.off_policy.parameter_dqn import PARAMETERS_DQN, DQNActionType, DQNActionSelectorType
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL, RIPEnvRewardType


class PARAMETERS_DOUBLE_PENDULUM_MATLAB_DQN(PARAMETERS_GENERAL, PARAMETERS_DQN):
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_MATLAB_DOUBLE_RIP_V0
    RL_ALGORITHM = RLAlgorithmName.DQN_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_MLP
    OPTIMIZER = OptimizerName.ADAM

    ENV_RESET = False
    ENV_RENDER = False

    TRAIN_STOP_EPISODE_REWARD = 60000  # MAX: 6.28 * 10000 = 62800 (Old), 90000 (New)
    TRAIN_STOP_EPISODE_REWARD_STD = 500
    STOP_PATIENCE_COUNT = 10

    REPLAY_BUFFER_SIZE = 100000
    TARGET_NET_SYNC_STEP_PERIOD = 10000

    MAX_GLOBAL_STEP = 1000000
    MAX_EPISODE_STEP = 10000

    EPSILON_MIN_STEP = 350000

    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01
    LEARNING_RATE = 0.001

    GAMMA = 0.99
    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50

    OMEGA = False

    TRAIN_STEP_FREQ = 2
    N_STEP = 2
    ACTION_SCALE = 2.5

    DOUBLE_PENDULUM_STATE_INFO = 0  # 1: ALL ARM INFO IGNORED, 2: ARM ANGLE INFO IGNORED (VELOCITY IS INCLUDED)

    UNIT_TIME = 0.006

    TYPE_OF_DQN_ACTION = DQNActionType.EPSILON_GREEDY
    TYPE_OF_DQN_ACTION_SELECTOR = DQNActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR
    TYPE_OF_RIP_REWARD = RIPEnvRewardType.NEW
