from codes.a_config._rl_parameters.off_policy.parameter_td3 import PARAMETERS_TD3, TD3ActionType, TD3ActionSelectorType
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL, RIPEnvRewardType


class PARAMETERS_DOUBLE_PENDULUM_MATLAB_TD3(PARAMETERS_GENERAL, PARAMETERS_TD3):
    ENV_RESET = False
    ENV_RENDER = False

    ENVIRONMENT_ID = EnvironmentName.PENDULUM_MATLAB_DOUBLE_RIP_V0
    RL_ALGORITHM = RLAlgorithmName.TD3_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.TD3_MLP

    VELOCITY_STATE_DENOMINATOR = 2500.0
    REWARD_DENOMINATOR = 9.0

    TRAIN_STOP_EPISODE_REWARD = 7000  # MAX: 6.28 * 10000 = 62800 (Old), 90000 (New)
    TRAIN_STOP_EPISODE_REWARD_STD = 100

    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1000000

    LEARNING_RATE = 0.002
    ACTOR_LEARNING_RATE = 0.0002

    TRAIN_STEP_FREQ = 4
    GAMMA = 0.999
    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50

    N_STEP = 2

    CLIP_GRAD = 0.1
    ACTION_SCALE = 2.5
    ACTION_SCALE_MODE = "EXTERNAL"

    NOISE_ENABLED = True

    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = 100

    TYPE_OF_RIP_REWARD = RIPEnvRewardType.NEW  # "old_version"

    TYPE_OF_TD3_ACTION = TD3ActionType.GAUSSIAN_NOISE
    TYPE_OF_TD3_ACTION_SELECTOR = TD3ActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR

    MAX_EPISODE_STEP_AT_PLAY = 10000000000
    MAX_EPISODE_STEP = 10000
    MAX_GLOBAL_STEP = 2000000
    EPSILON_MIN_STEP = 400000

    DOUBLE_PENDULUM_STATE_INFO = 0  # 1: ALL ARM INFO IGNORED, 2: ARM ANGLE INFO IGNORED (VELOCITY IS INCLUDED)

    UNIT_TIME = 0.006
