from codes.a_config._rl_parameters.off_policy.parameter_ddpg import PARAMETERS_DDPG
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_PENDULUM_MATLAB_DDPG(PARAMETERS_GENERAL, PARAMETERS_DDPG):
    ENV_RESET = True

    ENVIRONMENT_ID = EnvironmentName.PENDULUM_MATLAB_V0
    RL_ALGORITHM = RLAlgorithmName.DDPG_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_MLP
    #DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_GRU

    STOP_MEAN_EPISODE_REWARD = 75000
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 300000
    MAX_GLOBAL_STEP = 1000000
    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.0001
    TRAIN_STEP_FREQ = 1
    GAMMA = 0.999
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 50

    EPSILON_INIT = 0.9
    EPSILON_MIN = 0.001
    EPSILON_MIN_STEP = 500000

    N_STEP = 4
    OMEGA = False

    CLIP_GRAD = 0.1

    ACTION_SCALE = 3.0

    MODEL_SAVE_MODE = ModelSaveMode.FINAL_ONLY