from config.fast_rl_parameters.parameters_fast_rl_pong_dqn import PARAMETERS_FAST_RL_PONG_DQN
from config.fast_rl_parameters.parameters_fast_rl_cartpole_dqn import PARAMETERS_FAST_RL_CARTPOLE_DQN


class PARAMETERS(PARAMETERS_FAST_RL_CARTPOLE_DQN):
    pass