# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rip_service_pb2 as rip__service__pb2


class RDIPStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reset = channel.unary_unary(
                '/RDIP/reset',
                request_serializer=rip__service__pb2.RipRequest.SerializeToString,
                response_deserializer=rip__service__pb2.RipResponse.FromString,
                )
        self.step = channel.unary_unary(
                '/RDIP/step',
                request_serializer=rip__service__pb2.RipRequest.SerializeToString,
                response_deserializer=rip__service__pb2.RipResponse.FromString,
                )
        self.terminate = channel.unary_unary(
                '/RDIP/terminate',
                request_serializer=rip__service__pb2.RipRequest.SerializeToString,
                response_deserializer=rip__service__pb2.RipResponse.FromString,
                )
        self.initialize = channel.unary_unary(
                '/RDIP/initialize',
                request_serializer=rip__service__pb2.RipRequest.SerializeToString,
                response_deserializer=rip__service__pb2.RipResponse.FromString,
                )
        self.step_sync = channel.unary_unary(
                '/RDIP/step_sync',
                request_serializer=rip__service__pb2.RipRequest.SerializeToString,
                response_deserializer=rip__service__pb2.RipResponse.FromString,
                )
        self.reset_sync = channel.unary_unary(
                '/RDIP/reset_sync',
                request_serializer=rip__service__pb2.RipRequest.SerializeToString,
                response_deserializer=rip__service__pb2.RipResponse.FromString,
                )


class RDIPServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def step_sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset_sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RDIPServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=rip__service__pb2.RipRequest.FromString,
                    response_serializer=rip__service__pb2.RipResponse.SerializeToString,
            ),
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=rip__service__pb2.RipRequest.FromString,
                    response_serializer=rip__service__pb2.RipResponse.SerializeToString,
            ),
            'terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.terminate,
                    request_deserializer=rip__service__pb2.RipRequest.FromString,
                    response_serializer=rip__service__pb2.RipResponse.SerializeToString,
            ),
            'initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.initialize,
                    request_deserializer=rip__service__pb2.RipRequest.FromString,
                    response_serializer=rip__service__pb2.RipResponse.SerializeToString,
            ),
            'step_sync': grpc.unary_unary_rpc_method_handler(
                    servicer.step_sync,
                    request_deserializer=rip__service__pb2.RipRequest.FromString,
                    response_serializer=rip__service__pb2.RipResponse.SerializeToString,
            ),
            'reset_sync': grpc.unary_unary_rpc_method_handler(
                    servicer.reset_sync,
                    request_deserializer=rip__service__pb2.RipRequest.FromString,
                    response_serializer=rip__service__pb2.RipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RDIP', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RDIP(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RDIP/reset',
            rip__service__pb2.RipRequest.SerializeToString,
            rip__service__pb2.RipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RDIP/step',
            rip__service__pb2.RipRequest.SerializeToString,
            rip__service__pb2.RipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RDIP/terminate',
            rip__service__pb2.RipRequest.SerializeToString,
            rip__service__pb2.RipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RDIP/initialize',
            rip__service__pb2.RipRequest.SerializeToString,
            rip__service__pb2.RipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def step_sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RDIP/step_sync',
            rip__service__pb2.RipRequest.SerializeToString,
            rip__service__pb2.RipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset_sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RDIP/reset_sync',
            rip__service__pb2.RipRequest.SerializeToString,
            rip__service__pb2.RipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
