# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rip_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rip_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11rip_service.proto\"\x1b\n\nRipRequest\x12\r\n\x05value\x18\x01 \x01(\x02\"\xa5\x01\n\x0bRipResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tarm_angle\x18\x02 \x01(\x02\x12\x14\n\x0c\x61rm_velocity\x18\x03 \x01(\x02\x12\x14\n\x0clink_1_angle\x18\x04 \x01(\x02\x12\x17\n\x0flink_1_velocity\x18\x05 \x01(\x02\x12\x14\n\x0clink_2_angle\x18\x06 \x01(\x02\x12\x17\n\x0flink_2_velocity\x18\x07 \x01(\x02\x32{\n\x04RDIP\x12$\n\x05reset\x12\x0b.RipRequest\x1a\x0c.RipResponse\"\x00\x12#\n\x04step\x12\x0b.RipRequest\x1a\x0c.RipResponse\"\x00\x12(\n\tterminate\x12\x0b.RipRequest\x1a\x0c.RipResponse\"\x00\x62\x06proto3'
)




_RIPREQUEST = _descriptor.Descriptor(
  name='RipRequest',
  full_name='RipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='RipRequest.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)


_RIPRESPONSE = _descriptor.Descriptor(
  name='RipResponse',
  full_name='RipResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='RipResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arm_angle', full_name='RipResponse.arm_angle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arm_velocity', full_name='RipResponse.arm_velocity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link_1_angle', full_name='RipResponse.link_1_angle', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link_1_velocity', full_name='RipResponse.link_1_velocity', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link_2_angle', full_name='RipResponse.link_2_angle', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link_2_velocity', full_name='RipResponse.link_2_velocity', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['RipRequest'] = _RIPREQUEST
DESCRIPTOR.message_types_by_name['RipResponse'] = _RIPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RipRequest = _reflection.GeneratedProtocolMessageType('RipRequest', (_message.Message,), {
  'DESCRIPTOR' : _RIPREQUEST,
  '__module__' : 'rip_service_pb2'
  # @@protoc_insertion_point(class_scope:RipRequest)
  })
_sym_db.RegisterMessage(RipRequest)

RipResponse = _reflection.GeneratedProtocolMessageType('RipResponse', (_message.Message,), {
  'DESCRIPTOR' : _RIPRESPONSE,
  '__module__' : 'rip_service_pb2'
  # @@protoc_insertion_point(class_scope:RipResponse)
  })
_sym_db.RegisterMessage(RipResponse)



_RDIP = _descriptor.ServiceDescriptor(
  name='RDIP',
  full_name='RDIP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=218,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='RDIP.reset',
    index=0,
    containing_service=None,
    input_type=_RIPREQUEST,
    output_type=_RIPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='step',
    full_name='RDIP.step',
    index=1,
    containing_service=None,
    input_type=_RIPREQUEST,
    output_type=_RIPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='terminate',
    full_name='RDIP.terminate',
    index=2,
    containing_service=None,
    input_type=_RIPREQUEST,
    output_type=_RIPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RDIP)

DESCRIPTOR.services_by_name['RDIP'] = _RDIP

# @@protoc_insertion_point(module_scope)
