from g_utils.commons import AgentType


class ParameterDqn:
    AGENT_TYPE = AgentType.Dqn

    LEARNING_RATE = 0.0001

    EPSILON_INIT = 1.0
    EPSILON_FINAL = 0.1
    EPSILON_FINAL_TIME_STEP_PERCENT = 0.35

    BUFFER_CAPACITY = 10_000
    BATCH_SIZE = 64
    MIN_BUFFER_SIZE_FOR_TRAIN = BATCH_SIZE
    GAMMA = 0.99
    TARGET_SYNC_INTERVAL_TRAINING_STEPS = 50
