from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_QUANSER_RIP_DDPG(PARAMETERS_GENERAL):
    ENV_RENDER = False

    ENVIRONMENT_ID = EnvironmentName.QUANSER_SERVO_2
    RL_ALGORITHM = RLAlgorithmName.DDPG_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DETERMINISTIC_CONTINUOUS_ACTOR_CRITIC_MLP

    STOP_MEAN_EPISODE_REWARD = 3500
    STOP_PATIENCE_COUNT = 20
    REPLAY_BUFFER_SIZE = 100000
    MAX_GLOBAL_STEP = 5000000
    LEARNING_RATE = 0.0001
    ACTOR_LEARNING_RATE = 0.0001
    TRAIN_STEP_FREQ = 1
    GAMMA = 0.999

    MIN_REPLAY_SIZE_FOR_TRAIN = 256
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 50

    EPSILON_INIT = 500
    EPSILON_MIN = 0.001
    EPSILON_MIN_STEP = 1000000

    N_STEP = 4
    OMEGA = False
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False

    ACTION_SCALE = 150.0

    MODEL_SAVE_MODE = ModelSaveMode.TRAIN