import math

from codes.a_config._rl_parameters.off_policy.parameter_td3 import PARAMETERS_TD3, TD3ActionType, TD3ActionSelectorType
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_QUANSER_RIP_TD3(PARAMETERS_GENERAL, PARAMETERS_TD3):
    ENVIRONMENT_ID = EnvironmentName.QUANSER_SERVO_2
    RL_ALGORITHM = RLAlgorithmName.TD3_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.TD3_MLP

    VELOCITY_STATE_DENOMINATOR = 100.0
    REWARD_DENOMINATOR = math.pi

    TRAIN_STOP_EPISODE_REWARD = 7000  # MAX: 3.14 * 10000 = 31400
    TRAIN_STOP_EPISODE_REWARD_STD = 50.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1000000

    MAX_EPISODE_STEP_AT_PLAY = 10000000000
    MAX_EPISODE_STEP = 10000
    MAX_GLOBAL_STEP = 10000000
    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.0002
    GAMMA = 0.999

    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50

    N_STEP = 4
    OMEGA = False
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False

    TEST_NUM_EPISODES = 3

    DISTRIBUTIONAL = False
    NOISY_NET = False

    ACT_NOISE = 1
    NOISE_CLIP = 1

    NOISE_ENABLED = True
    OU_SIGMA = 2.5

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = 100

    TAU = 0.0005

    ACTION_SCALE = 250.0

    EPSILON_INIT = 0.5
    EPSILON_MIN = 0.01
    EPSILON_MIN_STEP = 1000000

    TYPE_OF_TD3_ACTION = TD3ActionType.GAUSSIAN_NOISE
    TYPE_OF_TD3_ACTION_SELECTOR = TD3ActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR

    TRAIN_STEP_FREQ = 2
    POLICY_UPDATE_FREQUENCY = 2 * TRAIN_STEP_FREQ

    UNIT_TIME = 0.006

