from codes.a_config._rl_parameters.off_policy.parameter_dqn import PARAMETERS_DQN, DQNActionType, DQNActionSelectorType
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_RIP_DQN(PARAMETERS_GENERAL, PARAMETERS_DQN):
    ENVIRONMENT_ID = EnvironmentName.REAL_DEVICE_RIP
    RL_ALGORITHM = RLAlgorithmName.DQN_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_MLP
    OPTIMIZER = OptimizerName.ADAM

    TRAIN_STOP_EPISODE_REWARD = 7000  # MAX: 6.28 * 5000 = 62800 (Old), 90000 (New)
    TRAIN_STOP_EPISODE_REWARD_STD = 50
    STOP_PATIENCE_COUNT = 10

    REPLAY_BUFFER_SIZE = 1000000
    TARGET_NET_SYNC_STEP_PERIOD = 10000

    MAX_GLOBAL_STEP = 10000000
    MAX_EPISODE_STEP = 10000
    MAX_EPISODE_STEP_AT_PLAY = 10000000000

    TRAIN_STEP_FREQ = 2
    AVG_EPISODE_SIZE_FOR_STAT = 50
    N_STEP = 2
    ACTION_SCALE = 500
    ENV_RESET = False
    TRAIN_ONLY_AFTER_EPISODE = False

    EPSILON_MIN_STEP = 3000000

    EPSILON_INIT = 1.0
    EPSILON_MIN = 0.01

    LEARNING_RATE = 0.001

    GAMMA = 0.999
    BATCH_SIZE = 128

    UNIT_TIME = 0.05

    TYPE_OF_DQN_ACTION = DQNActionType.EPSILON_GREEDY
    TYPE_OF_DQN_ACTION_SELECTOR = DQNActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR

    PENDULUM_STATE_INFO = 2  # 1: ALL ARM INFO IGNORED, 2: ARM ANGLE INFO IGNORED (VELOCITY IS INCLUDED)

    PERIODIC_MODEL_SAVE = True
