from codes.a_config._rl_parameters.off_policy.parameter_sac import PARAMETERS_SAC
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL, StochasticActionSelectorType, \
    StochasticActionType


class PARAMETERS_RIP_SAC(PARAMETERS_GENERAL, PARAMETERS_SAC):
    ENVIRONMENT_ID = EnvironmentName.REAL_DEVICE_RIP
    RL_ALGORITHM = RLAlgorithmName.CONTINUOUS_SAC_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.CONTINUOUS_SAC_MLP
    OPTIMIZER = OptimizerName.ADAM

    VELOCITY_STATE_DENOMINATOR = 500.0
    REWARD_DENOMINATOR = 3.14

    ENV_RESET = True
    TRAIN_STOP_EPISODE_REWARD = 700  # MAX: 6.28 * 5000 = 62800 (Old), 90000 (New)
    TRAIN_STOP_EPISODE_REWARD_STD = 50

    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1500000

    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.0001

    GAMMA = 0.99
    TAU = 0.0005

    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50

    N_STEP = 2

    CLIP_GRAD = 3.0
    ACTION_SCALE = 60

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = 100

    MAX_EPISODE_STEP_AT_PLAY = 10000000000
    MAX_EPISODE_STEP = 1000
    MAX_GLOBAL_STEP = 30000000

    UNIT_TIME = 0.007

    PENDULUM_STATE_INFO = 2  # 1: ALL ARM INFO IGNORED, 2: ARM ANGLE INFO IGNORED (VELOCITY IS INCLUDED)

    PERIODIC_MODEL_SAVE = True

    TYPE_OF_STOCHASTIC_ACTION = StochasticActionType.SAMPLE
    TYPE_OF_STOCHASTIC_ACTION_SELECTOR = StochasticActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR

    TRAIN_STEP_FREQ = 2
    POLICY_UPDATE_FREQUENCY = 2 * TRAIN_STEP_FREQ

    VERBOSE_TO_LOG = False


if __name__ == "__main__":
    params = PARAMETERS_RIP_SAC()
    for param in dir(params):
        if not param.startswith("__"):
            print(param, "=", getattr(params, param))


# /Users/yhhan/anaconda3/envs/link_rl_2/bin/python /Users/yhhan/git/link_rl/codes/a_config/e_real_device/parameters_rip_sac.py
# ACTION_SCALE = 500
# ACTOR_LEARNING_RATE = 0.0002
# ALPHA = 0.2
# ALPHA_LEARNING_RATE = 0.0001
# AVG_EPISODE_SIZE_FOR_STAT = 50
# AVG_STEP_SIZE_FOR_TRAIN_LOSS = 50
# BATCH_SIZE = 128
# CLIP_GRAD = 3.0
# CNN_CRITIC_HIDDEN_1_SIZE = 128
# CNN_CRITIC_HIDDEN_2_SIZE = 128
# CRITIC_LOSS_WEIGHT = 0.1
# CUDA_VISIBLE_DEVICES_NUMBER_LIST = 1, 2
# CURIOSITY_DRIVEN = False
# CURIOSITY_DRIVEN_BETA = 0.2
# CURIOSITY_DRIVEN_ETA = 1.0
# CURIOSITY_DRIVEN_LAMBDA = 0.1
# DEEP_LEARNING_MODEL = DeepLearningModelName.CONTINUOUS_SAC_MLP
# EMA_WINDOW = 10
# ENTROPY_LOSS_WEIGHT = 0.005
# ENTROPY_TUNING = False
# ENVIRONMENT_ID = EnvironmentName.REAL_DEVICE_RIP
# ENV_RESET = True
# EPSILON_INIT = None
# EPSILON_MIN = None
# EPSILON_MIN_STEP = None
# GAMMA = 0.99
# HIDDEN_1_SIZE = 128
# HIDDEN_2_SIZE = 128
# HIDDEN_3_SIZE = 128
# LEARNING_RATE = 0.002
# MAX_EPISODE_STEP = 1000
# MAX_EPISODE_STEP_AT_PLAY = 10000000000
# MAX_GLOBAL_STEP = 30000000
# MIN_REPLAY_SIZE_FOR_TRAIN = 2000
# MODEL_SAVE = False
# MODE_GRADIENTS_UPDATE = True
# MODE_PARAMETERS_TRANSFER = True
# MODE_SYNCHRONIZATION = True
# MQTT_LOG = False
# MQTT_PORT = 1883
# MQTT_SERVER = localhost
# MQTT_TOPIC_ACK = Ack
# MQTT_TOPIC_EPISODE_DETAIL = Episode_Detail
# MQTT_TOPIC_FAIL_DONE = Fail_Done
# MQTT_TOPIC_SUCCESS_DONE = Success_Done
# MQTT_TOPIC_TRANSFER_ACK = Transfer_Ack
# MQTT_TOPIC_UPDATE_ACK = Update_Ack
# MY_PLATFORM = COMMON
# NUM_ENVIRONMENTS = 1
# NUM_TRAIN_ONLY_AFTER_EPISODE = 100
# NUM_WORKERS = 1
# N_STEP = 2
# OPTIMIZER = OptimizerName.ADAM
# PENDULUM_STATE_INFO = 0
# PERIODIC_MODEL_SAVE = True
# PER_PROPORTIONAL = False
# PER_RANK_BASED = False
# POLICY_UPDATE_FREQUENCY = 4
# PYTHON_PATH = None
# REPLAY_BUFFER_SIZE = 1000000
# REWARD_DENOMINATOR = 3.14
# RL_ALGORITHM = RLAlgorithmName.CONTINUOUS_SAC_V0
# RNN_BIDIRECTIONAL = False
# RNN_HIDDEN_SIZE = 128
# RNN_NUM_LAYER = 3
# RNN_STEP_LENGTH = 2
# SEED = 1
# SERVER_IDX = None
# SOFT_TARGET_UPDATE = False
# SOFT_TARGET_UPDATE_TAU = 0.3
# SOFT_TRANSFER = False
# SOFT_TRANSFER_TAU = 0.3
# STOP_PATIENCE_COUNT = 10
# TARGET_NET_SYNC_STEP_PERIOD = 1000
# TAU = 0.0005
# TEST_NUM_EPISODES = 3
# TEST_PERIOD_EPISODES = 25
# TRAIN_ONLY_AFTER_EPISODE = False
# TRAIN_STEP_FREQ = 2
# TRAIN_STOP_EPISODE_REWARD = 700
# TRAIN_STOP_EPISODE_REWARD_STD = 50
# TRAJECTORY_LIMIT_SIZE = 200
# TRAJECTORY_SAMPLING = True
# TYPE_OF_STOCHASTIC_ACTION = StochasticActionType.SAMPLE
# TYPE_OF_STOCHASTIC_ACTION_SELECTOR = StochasticActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR
# UNIT_TIME = 0.006
# VELOCITY_STATE_DENOMINATOR = 500.0
# WANDB = True
