import math

from codes.a_config._rl_parameters.off_policy.parameter_sac import PARAMETERS_SAC
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL, StochasticActionType, StochasticActionSelectorType


class PARAMETERS_QUANSER_RIP_SAC(PARAMETERS_GENERAL, PARAMETERS_SAC):
    ENVIRONMENT_ID = EnvironmentName.QUANSER_SERVO_2
    RL_ALGORITHM = RLAlgorithmName.CONTINUOUS_SAC_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.CONTINUOUS_SAC_MLP

    VELOCITY_STATE_DENOMINATOR = 100.0
    REWARD_DENOMINATOR = math.pi

    TRAIN_STOP_EPISODE_REWARD = 950
    TRAIN_STOP_EPISODE_REWARD_STD = 50.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 1000000

    MAX_EPISODE_STEP_AT_PLAY = 10000000000
    MAX_EPISODE_STEP = 1000
    MAX_GLOBAL_STEP = 10000000

    LEARNING_RATE = 0.001
    ACTOR_LEARNING_RATE = 0.0002
    ALPHA_LEARNING_RATE = 0.001

    GAMMA = 0.99

    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 50

    N_STEP = 2
    OMEGA = False
    PER_PROPORTIONAL = False
    PER_RANK_BASED = False

    TEST_NUM_EPISODES = 3

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = 100

    TAU = 0.0005

    ACTION_SCALE = 250.0

    TYPE_OF_STOCHASTIC_ACTION = StochasticActionType.SAMPLE
    TYPE_OF_STOCHASTIC_ACTION_SELECTOR = StochasticActionSelectorType.SOMETIMES_BLOW_ACTION_SELECTOR

    UNIT_TIME = 0.006

    TRAIN_STEP_FREQ = 2
    POLICY_UPDATE_FREQUENCY = 2 * TRAIN_STEP_FREQ

    QUANSER_STATE_INFO = 1 #0:ALL INFO, 1: ALL ARM INFO IGNORED, 2: ARM ANGLE INFO IGNORED (VELOCITY IS INCLUDED)


