from codes.a_config._rl_parameters.off_policy.parameter_td3 import PARAMETERS_TD3, TD3ActionType, TD3ActionSelectorType
from codes.a_config._rl_parameters.on_policy.parameter_ppo import PARAMETERS_PPO
from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL, RIPEnvRewardType


class PARAMETERS_DOUBLE_RIP_PPO(PARAMETERS_GENERAL, PARAMETERS_PPO):
    ENVIRONMENT_ID = EnvironmentName.REAL_DEVICE_DOUBLE_RIP
    RL_ALGORITHM = RLAlgorithmName.CONTINUOUS_PPO_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.STOCHASTIC_CONTINUOUS_ACTOR_CRITIC_MLP
    OPTIMIZER = OptimizerName.ADAM

    TRAIN_STOP_EPISODE_REWARD = 650000  # MAX: 6.28 * 10000 = 62800 (Old), 4 * 10000 = 40000 (New)
    TRAIN_STOP_EPISODE_REWARD_STD = 3000
    STOP_PATIENCE_COUNT = 10

    MAX_EPISODE_STEP_AT_PLAY = 10000000000
    MAX_EPISODE_STEP = 10000
    MAX_GLOBAL_STEP = 40000000

    GAMMA = 0.999

    BATCH_SIZE = 128
    AVG_EPISODE_SIZE_FOR_STAT = 10

    ## PPO
    PPO_GAE_LAMBDA = 0.70
    PPO_TRAJECTORY_SIZE = 2049
    PPO_TRAJECTORY_BATCH_SIZE = 128
    ACTOR_LEARNING_RATE = 0.0002
    LEARNING_RATE = 0.001
    PPO_K_EPOCHS = 5
    PPO_EPSILON_CLIP = 0.2
    TRAIN_STEP_FREQ = 4
    N_STEP = 1

    TYPE_OF_RIP_REWARD = RIPEnvRewardType.NEW  # "old_version"
    DOUBLE_PENDULUM_STATE_INFO = 2  # 1: ALL ARM INFO IGNORED, 2: ARM ANGLE INFO IGNORED (VELOCITY IS INCLUDED)

    TRAIN_ONLY_AFTER_EPISODE = False
    NUM_TRAIN_ONLY_AFTER_EPISODE = 100

    ACTION_SCALE = 350.0

    ENV_RESET = False
    UNIT_TIME = 0.006
    PERIODIC_MODEL_SAVE = True


