class MULTI_GENETIC_NEURO_EVOLUTION_ALGORITHM:
    NOISE_STANDARD_DEVIATION = 0.01
    EVALUATION_EPISODES = 5

    WORKERS_COUNT = 5
    MAX_SEED = 2**32 - 1
    NUM_SEEDS_PER_WORKER = 100
    POPULATION_SIZE = NUM_SEEDS_PER_WORKER * WORKERS_COUNT
