from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_CARTPOLE_PG(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.CARTPOLE_V1
    RL_ALGORITHM = RLAlgorithmName.POLICY_GRADIENT_FAST_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.DUELING_DQN_MLP

    STOP_MEAN_EPISODE_REWARD = 195.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 50000
    MAX_GLOBAL_STEP = 100000
    LEARNING_RATE = 0.001
    GAMMA = 0.99
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 100
    DRAW_VIZ = True
    N_STEP = 10
    OMEGA = False