from codes.e_utils.names import *
from codes.a_config.parameters_general import PARAMETERS_GENERAL


class PARAMETERS_FAST_RL_PENDULUM_A2C(PARAMETERS_GENERAL):
    ENVIRONMENT_ID = EnvironmentName.PENDULUM_V0
    DEEP_LEARNING_MODEL = DeepLearningModelName.STOCHASTIC_CONTINUOUS_ACTOR_CRITIC_MLP
    RL_ALGORITHM = RLAlgorithmName.CONTINUOUS_A2C_FAST_V0
    OPTIMIZER = OptimizerName.ADAM

    STOP_MEAN_EPISODE_REWARD = 195.0
    STOP_PATIENCE_COUNT = 10
    REPLAY_BUFFER_SIZE = 50000
    MAX_GLOBAL_STEP = 800000
    LEARNING_RATE = 0.00005
    ACTOR_LEARNING_RATE = 0.00001
    GAMMA = 0.99
    BATCH_SIZE = 32
    AVG_EPISODE_SIZE_FOR_STAT = 100
    DRAW_VIZ = False
    N_STEP = 1

    CLIP_GRAD = 0.5

    ACTION_SCALE = 2.0
