class PARAMETERS_PPO:
    PPO_EPSILON_CLIP: 0.2
    PPO_GAE_LAMBDA: 0.70
    PPO_K_EPOCHS: 10
    PPO_TRAJECTORY_BATCH_SIZE: 128
    PPO_TRAJECTORY_SIZE: 2049
    ACTOR_LEARNING_RATE = 0.0002
    LEARNING_RATE = 0.001

    TRAIN_STEP_FREQ = 1
    N_STEP = 1

